In [18]:
import numpy as np

In [17]:
import pandas as pd

In [15]:
import csv

In [1]:
location = "DC_Properties.csv"

In [4]:
df= location

In [11]:
print(df.columns)

AttributeError: 'str' object has no attribute 'columns'

In [12]:
df.dtypes

AttributeError: 'str' object has no attribute 'dtypes'

In [14]:
df = pd.read_csv('DC_Properties.csv')

NameError: name 'pd' is not defined

In [1]:
import glob

In [2]:
all_data = pd.DataFrame()

NameError: name 'pd' is not defined

In [1]:
pd = 'DC_Properties.csv'

In [2]:
df = pd.read.csv (location)

AttributeError: 'str' object has no attribute 'read'

In [3]:
df = pd.read.csv ('DC_Properties.csv')

AttributeError: 'str' object has no attribute 'read'

In [4]:
df.head

NameError: name 'df' is not defined

In [5]:
df.count

NameError: name 'df' is not defined

In [1]:
pd = "DC_Properties.csv"

In [2]:
df = pd.DataFrame

AttributeError: 'str' object has no attribute 'DataFrame'

In [3]:
location = "DC_Properties.csv"

In [4]:
df = pd.read_csv(location)

AttributeError: 'str' object has no attribute 'read_csv'

In [5]:
import csv

In [6]:
import pandas as pd

In [7]:
df.head()

NameError: name 'df' is not defined

In [8]:
location = "DC_Properties.csv"

In [9]:
df = pd.read_csv(location)

C:\Users\kenbe\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (18,19,20,21,22,23,24,33,34,35,37,43,45) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [10]:
df.head

<bound method NDFrame.head of         Unnamed: 0  BATHRM  HF_BATHRM           HEAT AC  NUM_UNITS  ROOMS  \
0                0       4          0      Warm Cool  Y        2.0      8
1                1       3          1      Warm Cool  Y        2.0     11
2                2       3          1  Hot Water Rad  Y        2.0      9
3                3       3          1  Hot Water Rad  Y        2.0      8
4                4       2          1      Warm Cool  Y        1.0     11
5                5       3          2  Hot Water Rad  Y        1.0     10
6                6       1          0      Warm Cool  Y        2.0      5
7                7       3          1  Hot Water Rad  Y        2.0      8
8                8       3          1      Warm Cool  Y        2.0      7
9                9       1          1  Hot Water Rad  Y        1.0      6
10              10       3          0     Forced Air  N        3.0     12
11              11       5          0  Hot Water Rad  Y        3.0     16
12              12       2          0  Hot Water Rad  N        2.0      9
13              13       2          0      Warm Cool  Y        2.0     11
14              14       3          1      Warm Cool  Y        2.0      5
15              15       2          1      Warm Cool  Y        2.0      9
16              16       3          1      Warm Cool  Y        1.0      8
17              17       2          0  Hot Water Rad  N        1.0      6
18              18       3          1  Hot Water Rad  Y        2.0     10
19              19       3          1  Hot Water Rad  Y        2.0      9
20              20       3          1  Hot Water Rad  Y        1.0     14
21              21       3          0     Forced Air  Y        2.0     12
22              22       1          0     Forced Air  Y        1.0      6
23              23       2          1     Forced Air  Y        1.0      5
24              24       2          1  Hot Water Rad  Y        1.0      8
25              25       1          0  Hot Water Rad  N        1.0      8
26              26       1          0  Hot Water Rad  N        1.0     10
27              27       3          0  Hot Water Rad  Y        4.0      9
28              28       3          0      Warm Cool  Y        2.0     10
29              29       3          1     Forced Air  Y        2.0     11
...            ...     ...        ...            ... ..        ...    ...
158927      158927       2          0        Ht Pump  Y        NaN      6
158928      158928       2          1        Ht Pump  Y        NaN      5
158929      158929       2          1        Ht Pump  Y        NaN      5
158930      158930       2          0     Forced Air  N        NaN      4
158931      158931       2          1     Forced Air  N        NaN      4
158932      158932       2          1     Forced Air  N        NaN      4
158933      158933       2          0        Ht Pump  Y        NaN      4
158934      158934       1          1        Ht Pump  Y        NaN      3
158935      158935       1          0        Ht Pump  Y        NaN      3
158936      158936       1          0        Ht Pump  Y        NaN      3
158937      158937       1          0     Forced Air  Y        NaN      4
158938      158938       2          0      Warm Cool  Y        NaN      7
158939      158939       1          0     Forced Air  Y        NaN      4
158940      158940       2          0     Forced Air  Y        NaN      7
158941      158941       1          0     Forced Air  Y        NaN      4
158942      158942       2          0     Forced Air  Y        NaN      7
158943      158943       2          1     Forced Air  Y        NaN      5
158944      158944       2          1     Forced Air  Y        NaN      5
158945      158945       1          0     Forced Air  Y        NaN      3
158946      158946       1          0     Forced Air  Y        NaN      4
158947      158947       2          0     Forced Air  Y        NaN      4
158948      158948       2          0     Forced Air  Y        NaN      4
158949      158949       1          1     Forced Air  Y        NaN      4
158950      158950       3          0     Forced Air  Y        NaN      5
158951      158951       3          1     Forced Air  Y        NaN      5
158952      158952       1          0     Forced Air  Y        NaN      3
158953      158953       1          0     Forced Air  Y        NaN      4
158954      158954       2          0     Forced Air  Y        NaN      4
158955      158955       1          0      Warm Cool  Y        NaN      2
158956      158956       1          0      Warm Cool  Y        NaN      2

        BEDRM     AYB  YR_RMDL   ...     LONGITUDE       ASSESSMENT_NBHD  \
0           4  1910.0   1988.0   ...    -77.040832            Old City 2
1           5  1898.0   2007.0   ...    -77.040764            Old City 2
2           5  1910.0   2009.0   ...    -77.040678            Old City 2
3           5  1900.0   2003.0   ...    -77.040629            Old City 2
4           3  1913.0   2012.0   ...    -77.039361            Old City 2
5           5  1913.0      NaN   ...    -77.039715            Old City 2
6           2  1917.0   1988.0   ...    -77.041055            Old City 2
7           4  1906.0   2011.0   ...    -77.040129            Old City 2
8           3  1908.0   2008.0   ...    -77.039903            Old City 2
9           2  1908.0   1979.0   ...    -77.040081            Old City 2
10          5  1890.0   1950.0   ...    -77.040760            Old City 2
11          6  1905.0      NaN   ...    -77.039718            Old City 2
12          5  1894.0   1979.0   ...    -77.039569            Old City 2
13          5  1885.0   1979.0   ...    -77.039644            Old City 2
14          3  1917.0   2000.0   ...    -77.039716            Old City 2
15          4  1908.0   1990.0   ...    -77.039784            Old City 2
16          3  1908.0   2006.0   ...    -77.039844            Old City 2
17          3  1908.0   1987.0   ...    -77.039961            Old City 2
18          4  1908.0   2006.0   ...    -77.040020            Old City 2
19          3  1908.0   2013.0   ...    -77.040138            Old City 2
20          5  1880.0   2009.0   ...    -77.033774            Old City 2
21          3  1880.0   2009.0   ...    -77.033838            Old City 2
22          3  1880.0   2010.0   ...    -77.033925            Old City 2
23          3  1880.0   2010.0   ...    -77.033972            Old City 2
24          3  1880.0   2004.0   ...    -77.034070            Old City 2
25          4  1880.0   2010.0   ...    -77.034156            Old City 2
26          5  1900.0   2004.0   ...    -77.034258            Old City 2
27          3  1900.0   1963.0   ...    -77.034182            Old City 2
28          4  1900.0   1960.0   ...    -77.034119            Old City 2
29          3  1900.0   2014.0   ...    -77.034051            Old City 2
...       ...     ...      ...   ...           ...                   ...
158927      3  1993.0   1993.0   ...    -77.019274            Old City 2
158928      2  2013.0      NaN   ...    -77.019274            Old City 2
158929      2  2013.0      NaN   ...    -77.019274            Old City 2
158930      2  1900.0   2003.0   ...    -77.019243            Old City 2
158931      2  1900.0   2003.0   ...    -77.019243            Old City 2
158932      2  1900.0   2003.0   ...    -77.019243            Old City 2
158933      2  1880.0   2016.0   ...    -77.019243            Old City 2
158934      1  1880.0   2016.0   ...    -77.019243            Old City 2
158935      1  1880.0   2016.0   ...    -77.019243            Old City 2
158936      1  1880.0   2016.0   ...    -77.019243            Old City 2
158937      2  1992.0   1992.0   ...    -77.019420            Old City 2
158938      4  1992.0   1992.0   ...    -77.019420            Old City 2
158939      2  1992.0   1992.0   ...    -77.019420            Old City 2
158940      4  1992.0   1992.0   ...    -77.019420            Old City 2
158941      2  1992.0   1992.0   ...    -77.019420            Old City 2
158942      4  1992.0   1992.0   ...    -77.019420            Old City 2
158943      2  2004.0   2004.0   ...    -77.019420            Old City 2
158944      2  2004.0   2004.0   ...    -77.019420            Old City 2
158945      1  1938.0   2006.0   ...    -77.019420            Old City 2
158946      2  1938.0   2006.0   ...    -77.019420            Old City 2
158947      2  1938.0   2006.0   ...    -77.019420            Old City 2
158948      2  1938.0   2006.0   ...    -77.019420            Old City 2
158949      1  1938.0   2006.0   ...    -77.019420            Old City 2
158950      3  1938.0   2006.0   ...    -77.019420            Old City 2
158951      3  1938.0   2006.0   ...    -77.019420            Old City 2
158952      1  1938.0   2006.0   ...    -77.019420            Old City 2
158953      2  1938.0   2006.0   ...    -77.019420            Old City 2
158954      2  1920.0   2007.0   ...    -77.019420            Old City 2
158955      0  1965.0      NaN   ...    -77.018230  Southwest Waterfront
158956      0  1965.0      NaN   ...    -77.018230  Southwest Waterfront

       ASSESSMENT_SUBNBHD  CENSUS_TRACT CENSUS_BLOCK    WARD  SQUARE  \
0        040 D Old City 2        4201.0  004201 2006  Ward 2     152
1        040 D Old City 2        4201.0  004201 2006  Ward 2     152
2        040 D Old City 2        4201.0  004201 2006  Ward 2     152
3        040 D Old City 2        4201.0  004201 2006  Ward 2     152
4        040 D Old City 2        4201.0  004201 2006  Ward 2     152
5        040 D Old City 2        4201.0  004201 2006  Ward 2     152
6        040 D Old City 2        4201.0  004201 2005  Ward 2     152
7        040 D Old City 2        4201.0  004201 2005  Ward 2     152
8        040 D Old City 2        4201.0  004201 2005  Ward 2     152
9        040 D Old City 2        4201.0  004201 2005  Ward 2     152
10       040 D Old City 2        4201.0  004201 2005  Ward 2     152
11       040 D Old City 2        4201.0  004201 2005  Ward 2     152
12       040 D Old City 2        4201.0  004201 2005  Ward 2     152
13       040 D Old City 2        4201.0  004201 2005  Ward 2     152
14       040 D Old City 2        4201.0  004201 2005  Ward 2     152
15       040 D Old City 2        4201.0  004201 2005  Ward 2     152
16       040 D Old City 2        4201.0  004201 2005  Ward 2     152
17       040 D Old City 2        4201.0  004201 2005  Ward 2     152
18       040 D Old City 2        4201.0  004201 2005  Ward 2     152
19       040 D Old City 2        4201.0  004201 2005  Ward 2     152
20       040 E Old City 2        5201.0  005201 4003  Ward 2     208
21       040 E Old City 2        5201.0  005201 4003  Ward 2     208
22       040 E Old City 2        5201.0  005201 4003  Ward 2     208
23       040 E Old City 2        5201.0  005201 4003  Ward 2     208
24       040 E Old City 2        5201.0  005201 4003  Ward 2     208
25       040 E Old City 2        5201.0  005201 4003  Ward 2     208
26       040 E Old City 2        5201.0  005201 4003  Ward 2     208
27       040 E Old City 2        5201.0  005201 4003  Ward 2     208
28       040 E Old City 2        5201.0  005201 4003  Ward 2     208
29       040 E Old City 2        5201.0  005201 4003  Ward 2     208
...                   ...           ...          ...     ...     ...
158927   040 G Old City 2        4801.0          NaN  Ward 6     475
158928   040 G Old City 2        4801.0          NaN  Ward 6     475
158929   040 G Old City 2        4801.0          NaN  Ward 6     475
158930   040 B Old City 2        4801.0          NaN  Ward 6     476
158931   040 B Old City 2        4801.0          NaN  Ward 6     476
158932   040 B Old City 2        4801.0          NaN  Ward 6     476
158933   040 B Old City 2        4801.0          NaN  Ward 6     476
158934   040 B Old City 2        4801.0          NaN  Ward 6     476
158935   040 B Old City 2        4801.0          NaN  Ward 6     476
158936   040 B Old City 2        4801.0          NaN  Ward 6     476
158937   040 B Old City 2        4801.0          NaN  Ward 6     477
158938   040 B Old City 2        4801.0          NaN  Ward 6     477
158939   040 B Old City 2        4801.0          NaN  Ward 6     477
158940   040 B Old City 2        4801.0          NaN  Ward 6     477
158941   040 B Old City 2        4801.0          NaN  Ward 6     477
158942   040 B Old City 2        4801.0          NaN  Ward 6     477
158943   040 B Old City 2        4801.0          NaN  Ward 6     477
158944   040 B Old City 2        4801.0          NaN  Ward 6     477
158945   040 B Old City 2        4801.0          NaN  Ward 6     477
158946   040 B Old City 2        4801.0          NaN  Ward 6     477
158947   040 B Old City 2        4801.0          NaN  Ward 6     477
158948   040 B Old City 2        4801.0          NaN  Ward 6     477
158949   040 B Old City 2        4801.0          NaN  Ward 6     477
158950   040 B Old City 2        4801.0          NaN  Ward 6     477
158951   040 B Old City 2        4801.0          NaN  Ward 6     477
158952   040 B Old City 2        4801.0          NaN  Ward 6     477
158953   040 B Old City 2        4801.0          NaN  Ward 6     477
158954   040 B Old City 2        4801.0          NaN  Ward 6     477
158955                NaN       11000.0          NaN  Ward 6     504
158956                NaN       11000.0          NaN  Ward 6     504

                X          Y QUADRANT
0      -77.040429  38.914881       NW
1      -77.040429  38.914881       NW
2      -77.040429  38.914881       NW
3      -77.040429  38.914881       NW
4      -77.040429  38.914881       NW
5      -77.040429  38.914881       NW
6      -77.040429  38.914881       NW
7      -77.040429  38.914881       NW
8      -77.040429  38.914881       NW
9      -77.040429  38.914881       NW
10     -77.040429  38.914881       NW
11     -77.040429  38.914881       NW
12     -77.040429  38.914881       NW
13     -77.040429  38.914881       NW
14     -77.040429  38.914881       NW
15     -77.040429  38.914881       NW
16     -77.040429  38.914881       NW
17     -77.040429  38.914881       NW
18     -77.040429  38.914881       NW
19     -77.040429  38.914881       NW
20     -77.033366  38.911716       NW
21     -77.033366  38.911716       NW
22     -77.033366  38.911716       NW
23     -77.033366  38.911716       NW
24     -77.033366  38.911716       NW
25     -77.033366  38.911716       NW
26     -77.033366  38.911716       NW
27     -77.033366  38.911716       NW
28     -77.033366  38.911716       NW
29     -77.033366  38.911716       NW
...           ...        ...      ...
158927 -77.019277  38.914287       NW
158928 -77.019277  38.914287       NW
158929 -77.019277  38.914287       NW
158930 -77.019245  38.912954       NW
158931 -77.019245  38.912954       NW
158932 -77.019245  38.912954       NW
158933 -77.019245  38.912954       NW
158934 -77.019245  38.912954       NW
158935 -77.019245  38.912954       NW
158936 -77.019245  38.912954       NW
158937 -77.019422  38.911848       NW
158938 -77.019422  38.911848       NW
158939 -77.019422  38.911848       NW
158940 -77.019422  38.911848       NW
158941 -77.019422  38.911848       NW
158942 -77.019422  38.911848       NW
158943 -77.019422  38.911848       NW
158944 -77.019422  38.911848       NW
158945 -77.019422  38.911848       NW
158946 -77.019422  38.911848       NW
158947 -77.019422  38.911848       NW
158948 -77.019422  38.911848       NW
158949 -77.019422  38.911848       NW
158950 -77.019422  38.911848       NW
158951 -77.019422  38.911848       NW
158952 -77.019422  38.911848       NW
158953 -77.019422  38.911848       NW
158954 -77.019422  38.911848       NW
158955 -77.018232  38.872961       SW
158956 -77.018232  38.872961       SW

[158957 rows x 49 columns]>

In [11]:
df.columns

Index(['Unnamed: 0', 'BATHRM', 'HF_BATHRM', 'HEAT', 'AC', 'NUM_UNITS', 'ROOMS',
       'BEDRM', 'AYB', 'YR_RMDL', 'EYB', 'STORIES', 'SALEDATE', 'PRICE',
       'QUALIFIED', 'SALE_NUM', 'GBA', 'BLDG_NUM', 'STYLE', 'STRUCT', 'GRADE',
       'CNDTN', 'EXTWALL', 'ROOF', 'INTWALL', 'KITCHENS', 'FIREPLACES',
       'USECODE', 'LANDAREA', 'GIS_LAST_MOD_DTTM', 'SOURCE', 'CMPLX_NUM',
       'LIVING_GBA', 'FULLADDRESS', 'CITY', 'STATE', 'ZIPCODE', 'NATIONALGRID',
       'LATITUDE', 'LONGITUDE', 'ASSESSMENT_NBHD', 'ASSESSMENT_SUBNBHD',
       'CENSUS_TRACT', 'CENSUS_BLOCK', 'WARD', 'SQUARE', 'X', 'Y', 'QUADRANT'],
      dtype='object')

In [12]:
df.dtypes

Unnamed: 0              int64
BATHRM                  int64
HF_BATHRM               int64
HEAT                   object
AC                     object
NUM_UNITS             float64
ROOMS                   int64
BEDRM                   int64
AYB                   float64
YR_RMDL               float64
EYB                     int64
STORIES               float64
SALEDATE               object
PRICE                 float64
QUALIFIED              object
SALE_NUM                int64
GBA                   float64
BLDG_NUM                int64
STYLE                  object
STRUCT                 object
GRADE                  object
CNDTN                  object
EXTWALL                object
ROOF                   object
INTWALL                object
KITCHENS              float64
FIREPLACES              int64
USECODE                 int64
LANDAREA                int64
GIS_LAST_MOD_DTTM      object
SOURCE                 object
CMPLX_NUM             float64
LIVING_GBA            float64
FULLADDRESS            object
CITY                   object
STATE                  object
ZIPCODE               float64
NATIONALGRID           object
LATITUDE              float64
LONGITUDE             float64
ASSESSMENT_NBHD        object
ASSESSMENT_SUBNBHD     object
CENSUS_TRACT          float64
CENSUS_BLOCK           object
WARD                   object
SQUARE                 object
X                     float64
Y                     float64
QUADRANT               object
dtype: object

In [13]:
df.count

<bound method DataFrame.count of         Unnamed: 0  BATHRM  HF_BATHRM           HEAT AC  NUM_UNITS  ROOMS  \
0                0       4          0      Warm Cool  Y        2.0      8
1                1       3          1      Warm Cool  Y        2.0     11
2                2       3          1  Hot Water Rad  Y        2.0      9
3                3       3          1  Hot Water Rad  Y        2.0      8
4                4       2          1      Warm Cool  Y        1.0     11
5                5       3          2  Hot Water Rad  Y        1.0     10
6                6       1          0      Warm Cool  Y        2.0      5
7                7       3          1  Hot Water Rad  Y        2.0      8
8                8       3          1      Warm Cool  Y        2.0      7
9                9       1          1  Hot Water Rad  Y        1.0      6
10              10       3          0     Forced Air  N        3.0     12
11              11       5          0  Hot Water Rad  Y        3.0     16
12              12       2          0  Hot Water Rad  N        2.0      9
13              13       2          0      Warm Cool  Y        2.0     11
14              14       3          1      Warm Cool  Y        2.0      5
15              15       2          1      Warm Cool  Y        2.0      9
16              16       3          1      Warm Cool  Y        1.0      8
17              17       2          0  Hot Water Rad  N        1.0      6
18              18       3          1  Hot Water Rad  Y        2.0     10
19              19       3          1  Hot Water Rad  Y        2.0      9
20              20       3          1  Hot Water Rad  Y        1.0     14
21              21       3          0     Forced Air  Y        2.0     12
22              22       1          0     Forced Air  Y        1.0      6
23              23       2          1     Forced Air  Y        1.0      5
24              24       2          1  Hot Water Rad  Y        1.0      8
25              25       1          0  Hot Water Rad  N        1.0      8
26              26       1          0  Hot Water Rad  N        1.0     10
27              27       3          0  Hot Water Rad  Y        4.0      9
28              28       3          0      Warm Cool  Y        2.0     10
29              29       3          1     Forced Air  Y        2.0     11
...            ...     ...        ...            ... ..        ...    ...
158927      158927       2          0        Ht Pump  Y        NaN      6
158928      158928       2          1        Ht Pump  Y        NaN      5
158929      158929       2          1        Ht Pump  Y        NaN      5
158930      158930       2          0     Forced Air  N        NaN      4
158931      158931       2          1     Forced Air  N        NaN      4
158932      158932       2          1     Forced Air  N        NaN      4
158933      158933       2          0        Ht Pump  Y        NaN      4
158934      158934       1          1        Ht Pump  Y        NaN      3
158935      158935       1          0        Ht Pump  Y        NaN      3
158936      158936       1          0        Ht Pump  Y        NaN      3
158937      158937       1          0     Forced Air  Y        NaN      4
158938      158938       2          0      Warm Cool  Y        NaN      7
158939      158939       1          0     Forced Air  Y        NaN      4
158940      158940       2          0     Forced Air  Y        NaN      7
158941      158941       1          0     Forced Air  Y        NaN      4
158942      158942       2          0     Forced Air  Y        NaN      7
158943      158943       2          1     Forced Air  Y        NaN      5
158944      158944       2          1     Forced Air  Y        NaN      5
158945      158945       1          0     Forced Air  Y        NaN      3
158946      158946       1          0     Forced Air  Y        NaN      4
158947      158947       2          0     Forced Air  Y        NaN      4
158948      158948       2          0     Forced Air  Y        NaN      4
158949      158949       1          1     Forced Air  Y        NaN      4
158950      158950       3          0     Forced Air  Y        NaN      5
158951      158951       3          1     Forced Air  Y        NaN      5
158952      158952       1          0     Forced Air  Y        NaN      3
158953      158953       1          0     Forced Air  Y        NaN      4
158954      158954       2          0     Forced Air  Y        NaN      4
158955      158955       1          0      Warm Cool  Y        NaN      2
158956      158956       1          0      Warm Cool  Y        NaN      2

        BEDRM     AYB  YR_RMDL   ...     LONGITUDE       ASSESSMENT_NBHD  \
0           4  1910.0   1988.0   ...    -77.040832            Old City 2
1           5  1898.0   2007.0   ...    -77.040764            Old City 2
2           5  1910.0   2009.0   ...    -77.040678            Old City 2
3           5  1900.0   2003.0   ...    -77.040629            Old City 2
4           3  1913.0   2012.0   ...    -77.039361            Old City 2
5           5  1913.0      NaN   ...    -77.039715            Old City 2
6           2  1917.0   1988.0   ...    -77.041055            Old City 2
7           4  1906.0   2011.0   ...    -77.040129            Old City 2
8           3  1908.0   2008.0   ...    -77.039903            Old City 2
9           2  1908.0   1979.0   ...    -77.040081            Old City 2
10          5  1890.0   1950.0   ...    -77.040760            Old City 2
11          6  1905.0      NaN   ...    -77.039718            Old City 2
12          5  1894.0   1979.0   ...    -77.039569            Old City 2
13          5  1885.0   1979.0   ...    -77.039644            Old City 2
14          3  1917.0   2000.0   ...    -77.039716            Old City 2
15          4  1908.0   1990.0   ...    -77.039784            Old City 2
16          3  1908.0   2006.0   ...    -77.039844            Old City 2
17          3  1908.0   1987.0   ...    -77.039961            Old City 2
18          4  1908.0   2006.0   ...    -77.040020            Old City 2
19          3  1908.0   2013.0   ...    -77.040138            Old City 2
20          5  1880.0   2009.0   ...    -77.033774            Old City 2
21          3  1880.0   2009.0   ...    -77.033838            Old City 2
22          3  1880.0   2010.0   ...    -77.033925            Old City 2
23          3  1880.0   2010.0   ...    -77.033972            Old City 2
24          3  1880.0   2004.0   ...    -77.034070            Old City 2
25          4  1880.0   2010.0   ...    -77.034156            Old City 2
26          5  1900.0   2004.0   ...    -77.034258            Old City 2
27          3  1900.0   1963.0   ...    -77.034182            Old City 2
28          4  1900.0   1960.0   ...    -77.034119            Old City 2
29          3  1900.0   2014.0   ...    -77.034051            Old City 2
...       ...     ...      ...   ...           ...                   ...
158927      3  1993.0   1993.0   ...    -77.019274            Old City 2
158928      2  2013.0      NaN   ...    -77.019274            Old City 2
158929      2  2013.0      NaN   ...    -77.019274            Old City 2
158930      2  1900.0   2003.0   ...    -77.019243            Old City 2
158931      2  1900.0   2003.0   ...    -77.019243            Old City 2
158932      2  1900.0   2003.0   ...    -77.019243            Old City 2
158933      2  1880.0   2016.0   ...    -77.019243            Old City 2
158934      1  1880.0   2016.0   ...    -77.019243            Old City 2
158935      1  1880.0   2016.0   ...    -77.019243            Old City 2
158936      1  1880.0   2016.0   ...    -77.019243            Old City 2
158937      2  1992.0   1992.0   ...    -77.019420            Old City 2
158938      4  1992.0   1992.0   ...    -77.019420            Old City 2
158939      2  1992.0   1992.0   ...    -77.019420            Old City 2
158940      4  1992.0   1992.0   ...    -77.019420            Old City 2
158941      2  1992.0   1992.0   ...    -77.019420            Old City 2
158942      4  1992.0   1992.0   ...    -77.019420            Old City 2
158943      2  2004.0   2004.0   ...    -77.019420            Old City 2
158944      2  2004.0   2004.0   ...    -77.019420            Old City 2
158945      1  1938.0   2006.0   ...    -77.019420            Old City 2
158946      2  1938.0   2006.0   ...    -77.019420            Old City 2
158947      2  1938.0   2006.0   ...    -77.019420            Old City 2
158948      2  1938.0   2006.0   ...    -77.019420            Old City 2
158949      1  1938.0   2006.0   ...    -77.019420            Old City 2
158950      3  1938.0   2006.0   ...    -77.019420            Old City 2
158951      3  1938.0   2006.0   ...    -77.019420            Old City 2
158952      1  1938.0   2006.0   ...    -77.019420            Old City 2
158953      2  1938.0   2006.0   ...    -77.019420            Old City 2
158954      2  1920.0   2007.0   ...    -77.019420            Old City 2
158955      0  1965.0      NaN   ...    -77.018230  Southwest Waterfront
158956      0  1965.0      NaN   ...    -77.018230  Southwest Waterfront

       ASSESSMENT_SUBNBHD  CENSUS_TRACT CENSUS_BLOCK    WARD  SQUARE  \
0        040 D Old City 2        4201.0  004201 2006  Ward 2     152
1        040 D Old City 2        4201.0  004201 2006  Ward 2     152
2        040 D Old City 2        4201.0  004201 2006  Ward 2     152
3        040 D Old City 2        4201.0  004201 2006  Ward 2     152
4        040 D Old City 2        4201.0  004201 2006  Ward 2     152
5        040 D Old City 2        4201.0  004201 2006  Ward 2     152
6        040 D Old City 2        4201.0  004201 2005  Ward 2     152
7        040 D Old City 2        4201.0  004201 2005  Ward 2     152
8        040 D Old City 2        4201.0  004201 2005  Ward 2     152
9        040 D Old City 2        4201.0  004201 2005  Ward 2     152
10       040 D Old City 2        4201.0  004201 2005  Ward 2     152
11       040 D Old City 2        4201.0  004201 2005  Ward 2     152
12       040 D Old City 2        4201.0  004201 2005  Ward 2     152
13       040 D Old City 2        4201.0  004201 2005  Ward 2     152
14       040 D Old City 2        4201.0  004201 2005  Ward 2     152
15       040 D Old City 2        4201.0  004201 2005  Ward 2     152
16       040 D Old City 2        4201.0  004201 2005  Ward 2     152
17       040 D Old City 2        4201.0  004201 2005  Ward 2     152
18       040 D Old City 2        4201.0  004201 2005  Ward 2     152
19       040 D Old City 2        4201.0  004201 2005  Ward 2     152
20       040 E Old City 2        5201.0  005201 4003  Ward 2     208
21       040 E Old City 2        5201.0  005201 4003  Ward 2     208
22       040 E Old City 2        5201.0  005201 4003  Ward 2     208
23       040 E Old City 2        5201.0  005201 4003  Ward 2     208
24       040 E Old City 2        5201.0  005201 4003  Ward 2     208
25       040 E Old City 2        5201.0  005201 4003  Ward 2     208
26       040 E Old City 2        5201.0  005201 4003  Ward 2     208
27       040 E Old City 2        5201.0  005201 4003  Ward 2     208
28       040 E Old City 2        5201.0  005201 4003  Ward 2     208
29       040 E Old City 2        5201.0  005201 4003  Ward 2     208
...                   ...           ...          ...     ...     ...
158927   040 G Old City 2        4801.0          NaN  Ward 6     475
158928   040 G Old City 2        4801.0          NaN  Ward 6     475
158929   040 G Old City 2        4801.0          NaN  Ward 6     475
158930   040 B Old City 2        4801.0          NaN  Ward 6     476
158931   040 B Old City 2        4801.0          NaN  Ward 6     476
158932   040 B Old City 2        4801.0          NaN  Ward 6     476
158933   040 B Old City 2        4801.0          NaN  Ward 6     476
158934   040 B Old City 2        4801.0          NaN  Ward 6     476
158935   040 B Old City 2        4801.0          NaN  Ward 6     476
158936   040 B Old City 2        4801.0          NaN  Ward 6     476
158937   040 B Old City 2        4801.0          NaN  Ward 6     477
158938   040 B Old City 2        4801.0          NaN  Ward 6     477
158939   040 B Old City 2        4801.0          NaN  Ward 6     477
158940   040 B Old City 2        4801.0          NaN  Ward 6     477
158941   040 B Old City 2        4801.0          NaN  Ward 6     477
158942   040 B Old City 2        4801.0          NaN  Ward 6     477
158943   040 B Old City 2        4801.0          NaN  Ward 6     477
158944   040 B Old City 2        4801.0          NaN  Ward 6     477
158945   040 B Old City 2        4801.0          NaN  Ward 6     477
158946   040 B Old City 2        4801.0          NaN  Ward 6     477
158947   040 B Old City 2        4801.0          NaN  Ward 6     477
158948   040 B Old City 2        4801.0          NaN  Ward 6     477
158949   040 B Old City 2        4801.0          NaN  Ward 6     477
158950   040 B Old City 2        4801.0          NaN  Ward 6     477
158951   040 B Old City 2        4801.0          NaN  Ward 6     477
158952   040 B Old City 2        4801.0          NaN  Ward 6     477
158953   040 B Old City 2        4801.0          NaN  Ward 6     477
158954   040 B Old City 2        4801.0          NaN  Ward 6     477
158955                NaN       11000.0          NaN  Ward 6     504
158956                NaN       11000.0          NaN  Ward 6     504

                X          Y QUADRANT
0      -77.040429  38.914881       NW
1      -77.040429  38.914881       NW
2      -77.040429  38.914881       NW
3      -77.040429  38.914881       NW
4      -77.040429  38.914881       NW
5      -77.040429  38.914881       NW
6      -77.040429  38.914881       NW
7      -77.040429  38.914881       NW
8      -77.040429  38.914881       NW
9      -77.040429  38.914881       NW
10     -77.040429  38.914881       NW
11     -77.040429  38.914881       NW
12     -77.040429  38.914881       NW
13     -77.040429  38.914881       NW
14     -77.040429  38.914881       NW
15     -77.040429  38.914881       NW
16     -77.040429  38.914881       NW
17     -77.040429  38.914881       NW
18     -77.040429  38.914881       NW
19     -77.040429  38.914881       NW
20     -77.033366  38.911716       NW
21     -77.033366  38.911716       NW
22     -77.033366  38.911716       NW
23     -77.033366  38.911716       NW
24     -77.033366  38.911716       NW
25     -77.033366  38.911716       NW
26     -77.033366  38.911716       NW
27     -77.033366  38.911716       NW
28     -77.033366  38.911716       NW
29     -77.033366  38.911716       NW
...           ...        ...      ...
158927 -77.019277  38.914287       NW
158928 -77.019277  38.914287       NW
158929 -77.019277  38.914287       NW
158930 -77.019245  38.912954       NW
158931 -77.019245  38.912954       NW
158932 -77.019245  38.912954       NW
158933 -77.019245  38.912954       NW
158934 -77.019245  38.912954       NW
158935 -77.019245  38.912954       NW
158936 -77.019245  38.912954       NW
158937 -77.019422  38.911848       NW
158938 -77.019422  38.911848       NW
158939 -77.019422  38.911848       NW
158940 -77.019422  38.911848       NW
158941 -77.019422  38.911848       NW
158942 -77.019422  38.911848       NW
158943 -77.019422  38.911848       NW
158944 -77.019422  38.911848       NW
158945 -77.019422  38.911848       NW
158946 -77.019422  38.911848       NW
158947 -77.019422  38.911848       NW
158948 -77.019422  38.911848       NW
158949 -77.019422  38.911848       NW
158950 -77.019422  38.911848       NW
158951 -77.019422  38.911848       NW
158952 -77.019422  38.911848       NW
158953 -77.019422  38.911848       NW
158954 -77.019422  38.911848       NW
158955 -77.018232  38.872961       SW
158956 -77.018232  38.872961       SW

[158957 rows x 49 columns]>

In [15]:
df.count

<bound method DataFrame.count of         Unnamed: 0  BATHRM  HF_BATHRM           HEAT AC  NUM_UNITS  ROOMS  \
0                0       4          0      Warm Cool  Y        2.0      8
1                1       3          1      Warm Cool  Y        2.0     11
2                2       3          1  Hot Water Rad  Y        2.0      9
3                3       3          1  Hot Water Rad  Y        2.0      8
4                4       2          1      Warm Cool  Y        1.0     11
5                5       3          2  Hot Water Rad  Y        1.0     10
6                6       1          0      Warm Cool  Y        2.0      5
7                7       3          1  Hot Water Rad  Y        2.0      8
8                8       3          1      Warm Cool  Y        2.0      7
9                9       1          1  Hot Water Rad  Y        1.0      6
10              10       3          0     Forced Air  N        3.0     12
11              11       5          0  Hot Water Rad  Y        3.0     16
12              12       2          0  Hot Water Rad  N        2.0      9
13              13       2          0      Warm Cool  Y        2.0     11
14              14       3          1      Warm Cool  Y        2.0      5
15              15       2          1      Warm Cool  Y        2.0      9
16              16       3          1      Warm Cool  Y        1.0      8
17              17       2          0  Hot Water Rad  N        1.0      6
18              18       3          1  Hot Water Rad  Y        2.0     10
19              19       3          1  Hot Water Rad  Y        2.0      9
20              20       3          1  Hot Water Rad  Y        1.0     14
21              21       3          0     Forced Air  Y        2.0     12
22              22       1          0     Forced Air  Y        1.0      6
23              23       2          1     Forced Air  Y        1.0      5
24              24       2          1  Hot Water Rad  Y        1.0      8
25              25       1          0  Hot Water Rad  N        1.0      8
26              26       1          0  Hot Water Rad  N        1.0     10
27              27       3          0  Hot Water Rad  Y        4.0      9
28              28       3          0      Warm Cool  Y        2.0     10
29              29       3          1     Forced Air  Y        2.0     11
...            ...     ...        ...            ... ..        ...    ...
158927      158927       2          0        Ht Pump  Y        NaN      6
158928      158928       2          1        Ht Pump  Y        NaN      5
158929      158929       2          1        Ht Pump  Y        NaN      5
158930      158930       2          0     Forced Air  N        NaN      4
158931      158931       2          1     Forced Air  N        NaN      4
158932      158932       2          1     Forced Air  N        NaN      4
158933      158933       2          0        Ht Pump  Y        NaN      4
158934      158934       1          1        Ht Pump  Y        NaN      3
158935      158935       1          0        Ht Pump  Y        NaN      3
158936      158936       1          0        Ht Pump  Y        NaN      3
158937      158937       1          0     Forced Air  Y        NaN      4
158938      158938       2          0      Warm Cool  Y        NaN      7
158939      158939       1          0     Forced Air  Y        NaN      4
158940      158940       2          0     Forced Air  Y        NaN      7
158941      158941       1          0     Forced Air  Y        NaN      4
158942      158942       2          0     Forced Air  Y        NaN      7
158943      158943       2          1     Forced Air  Y        NaN      5
158944      158944       2          1     Forced Air  Y        NaN      5
158945      158945       1          0     Forced Air  Y        NaN      3
158946      158946       1          0     Forced Air  Y        NaN      4
158947      158947       2          0     Forced Air  Y        NaN      4
158948      158948       2          0     Forced Air  Y        NaN      4
158949      158949       1          1     Forced Air  Y        NaN      4
158950      158950       3          0     Forced Air  Y        NaN      5
158951      158951       3          1     Forced Air  Y        NaN      5
158952      158952       1          0     Forced Air  Y        NaN      3
158953      158953       1          0     Forced Air  Y        NaN      4
158954      158954       2          0     Forced Air  Y        NaN      4
158955      158955       1          0      Warm Cool  Y        NaN      2
158956      158956       1          0      Warm Cool  Y        NaN      2

        BEDRM     AYB  YR_RMDL   ...     LONGITUDE       ASSESSMENT_NBHD  \
0           4  1910.0   1988.0   ...    -77.040832            Old City 2
1           5  1898.0   2007.0   ...    -77.040764            Old City 2
2           5  1910.0   2009.0   ...    -77.040678            Old City 2
3           5  1900.0   2003.0   ...    -77.040629            Old City 2
4           3  1913.0   2012.0   ...    -77.039361            Old City 2
5           5  1913.0      NaN   ...    -77.039715            Old City 2
6           2  1917.0   1988.0   ...    -77.041055            Old City 2
7           4  1906.0   2011.0   ...    -77.040129            Old City 2
8           3  1908.0   2008.0   ...    -77.039903            Old City 2
9           2  1908.0   1979.0   ...    -77.040081            Old City 2
10          5  1890.0   1950.0   ...    -77.040760            Old City 2
11          6  1905.0      NaN   ...    -77.039718            Old City 2
12          5  1894.0   1979.0   ...    -77.039569            Old City 2
13          5  1885.0   1979.0   ...    -77.039644            Old City 2
14          3  1917.0   2000.0   ...    -77.039716            Old City 2
15          4  1908.0   1990.0   ...    -77.039784            Old City 2
16          3  1908.0   2006.0   ...    -77.039844            Old City 2
17          3  1908.0   1987.0   ...    -77.039961            Old City 2
18          4  1908.0   2006.0   ...    -77.040020            Old City 2
19          3  1908.0   2013.0   ...    -77.040138            Old City 2
20          5  1880.0   2009.0   ...    -77.033774            Old City 2
21          3  1880.0   2009.0   ...    -77.033838            Old City 2
22          3  1880.0   2010.0   ...    -77.033925            Old City 2
23          3  1880.0   2010.0   ...    -77.033972            Old City 2
24          3  1880.0   2004.0   ...    -77.034070            Old City 2
25          4  1880.0   2010.0   ...    -77.034156            Old City 2
26          5  1900.0   2004.0   ...    -77.034258            Old City 2
27          3  1900.0   1963.0   ...    -77.034182            Old City 2
28          4  1900.0   1960.0   ...    -77.034119            Old City 2
29          3  1900.0   2014.0   ...    -77.034051            Old City 2
...       ...     ...      ...   ...           ...                   ...
158927      3  1993.0   1993.0   ...    -77.019274            Old City 2
158928      2  2013.0      NaN   ...    -77.019274            Old City 2
158929      2  2013.0      NaN   ...    -77.019274            Old City 2
158930      2  1900.0   2003.0   ...    -77.019243            Old City 2
158931      2  1900.0   2003.0   ...    -77.019243            Old City 2
158932      2  1900.0   2003.0   ...    -77.019243            Old City 2
158933      2  1880.0   2016.0   ...    -77.019243            Old City 2
158934      1  1880.0   2016.0   ...    -77.019243            Old City 2
158935      1  1880.0   2016.0   ...    -77.019243            Old City 2
158936      1  1880.0   2016.0   ...    -77.019243            Old City 2
158937      2  1992.0   1992.0   ...    -77.019420            Old City 2
158938      4  1992.0   1992.0   ...    -77.019420            Old City 2
158939      2  1992.0   1992.0   ...    -77.019420            Old City 2
158940      4  1992.0   1992.0   ...    -77.019420            Old City 2
158941      2  1992.0   1992.0   ...    -77.019420            Old City 2
158942      4  1992.0   1992.0   ...    -77.019420            Old City 2
158943      2  2004.0   2004.0   ...    -77.019420            Old City 2
158944      2  2004.0   2004.0   ...    -77.019420            Old City 2
158945      1  1938.0   2006.0   ...    -77.019420            Old City 2
158946      2  1938.0   2006.0   ...    -77.019420            Old City 2
158947      2  1938.0   2006.0   ...    -77.019420            Old City 2
158948      2  1938.0   2006.0   ...    -77.019420            Old City 2
158949      1  1938.0   2006.0   ...    -77.019420            Old City 2
158950      3  1938.0   2006.0   ...    -77.019420            Old City 2
158951      3  1938.0   2006.0   ...    -77.019420            Old City 2
158952      1  1938.0   2006.0   ...    -77.019420            Old City 2
158953      2  1938.0   2006.0   ...    -77.019420            Old City 2
158954      2  1920.0   2007.0   ...    -77.019420            Old City 2
158955      0  1965.0      NaN   ...    -77.018230  Southwest Waterfront
158956      0  1965.0      NaN   ...    -77.018230  Southwest Waterfront

       ASSESSMENT_SUBNBHD  CENSUS_TRACT CENSUS_BLOCK    WARD  SQUARE  \
0        040 D Old City 2        4201.0  004201 2006  Ward 2     152
1        040 D Old City 2        4201.0  004201 2006  Ward 2     152
2        040 D Old City 2        4201.0  004201 2006  Ward 2     152
3        040 D Old City 2        4201.0  004201 2006  Ward 2     152
4        040 D Old City 2        4201.0  004201 2006  Ward 2     152
5        040 D Old City 2        4201.0  004201 2006  Ward 2     152
6        040 D Old City 2        4201.0  004201 2005  Ward 2     152
7        040 D Old City 2        4201.0  004201 2005  Ward 2     152
8        040 D Old City 2        4201.0  004201 2005  Ward 2     152
9        040 D Old City 2        4201.0  004201 2005  Ward 2     152
10       040 D Old City 2        4201.0  004201 2005  Ward 2     152
11       040 D Old City 2        4201.0  004201 2005  Ward 2     152
12       040 D Old City 2        4201.0  004201 2005  Ward 2     152
13       040 D Old City 2        4201.0  004201 2005  Ward 2     152
14       040 D Old City 2        4201.0  004201 2005  Ward 2     152
15       040 D Old City 2        4201.0  004201 2005  Ward 2     152
16       040 D Old City 2        4201.0  004201 2005  Ward 2     152
17       040 D Old City 2        4201.0  004201 2005  Ward 2     152
18       040 D Old City 2        4201.0  004201 2005  Ward 2     152
19       040 D Old City 2        4201.0  004201 2005  Ward 2     152
20       040 E Old City 2        5201.0  005201 4003  Ward 2     208
21       040 E Old City 2        5201.0  005201 4003  Ward 2     208
22       040 E Old City 2        5201.0  005201 4003  Ward 2     208
23       040 E Old City 2        5201.0  005201 4003  Ward 2     208
24       040 E Old City 2        5201.0  005201 4003  Ward 2     208
25       040 E Old City 2        5201.0  005201 4003  Ward 2     208
26       040 E Old City 2        5201.0  005201 4003  Ward 2     208
27       040 E Old City 2        5201.0  005201 4003  Ward 2     208
28       040 E Old City 2        5201.0  005201 4003  Ward 2     208
29       040 E Old City 2        5201.0  005201 4003  Ward 2     208
...                   ...           ...          ...     ...     ...
158927   040 G Old City 2        4801.0          NaN  Ward 6     475
158928   040 G Old City 2        4801.0          NaN  Ward 6     475
158929   040 G Old City 2        4801.0          NaN  Ward 6     475
158930   040 B Old City 2        4801.0          NaN  Ward 6     476
158931   040 B Old City 2        4801.0          NaN  Ward 6     476
158932   040 B Old City 2        4801.0          NaN  Ward 6     476
158933   040 B Old City 2        4801.0          NaN  Ward 6     476
158934   040 B Old City 2        4801.0          NaN  Ward 6     476
158935   040 B Old City 2        4801.0          NaN  Ward 6     476
158936   040 B Old City 2        4801.0          NaN  Ward 6     476
158937   040 B Old City 2        4801.0          NaN  Ward 6     477
158938   040 B Old City 2        4801.0          NaN  Ward 6     477
158939   040 B Old City 2        4801.0          NaN  Ward 6     477
158940   040 B Old City 2        4801.0          NaN  Ward 6     477
158941   040 B Old City 2        4801.0          NaN  Ward 6     477
158942   040 B Old City 2        4801.0          NaN  Ward 6     477
158943   040 B Old City 2        4801.0          NaN  Ward 6     477
158944   040 B Old City 2        4801.0          NaN  Ward 6     477
158945   040 B Old City 2        4801.0          NaN  Ward 6     477
158946   040 B Old City 2        4801.0          NaN  Ward 6     477
158947   040 B Old City 2        4801.0          NaN  Ward 6     477
158948   040 B Old City 2        4801.0          NaN  Ward 6     477
158949   040 B Old City 2        4801.0          NaN  Ward 6     477
158950   040 B Old City 2        4801.0          NaN  Ward 6     477
158951   040 B Old City 2        4801.0          NaN  Ward 6     477
158952   040 B Old City 2        4801.0          NaN  Ward 6     477
158953   040 B Old City 2        4801.0          NaN  Ward 6     477
158954   040 B Old City 2        4801.0          NaN  Ward 6     477
158955                NaN       11000.0          NaN  Ward 6     504
158956                NaN       11000.0          NaN  Ward 6     504

                X          Y QUADRANT
0      -77.040429  38.914881       NW
1      -77.040429  38.914881       NW
2      -77.040429  38.914881       NW
3      -77.040429  38.914881       NW
4      -77.040429  38.914881       NW
5      -77.040429  38.914881       NW
6      -77.040429  38.914881       NW
7      -77.040429  38.914881       NW
8      -77.040429  38.914881       NW
9      -77.040429  38.914881       NW
10     -77.040429  38.914881       NW
11     -77.040429  38.914881       NW
12     -77.040429  38.914881       NW
13     -77.040429  38.914881       NW
14     -77.040429  38.914881       NW
15     -77.040429  38.914881       NW
16     -77.040429  38.914881       NW
17     -77.040429  38.914881       NW
18     -77.040429  38.914881       NW
19     -77.040429  38.914881       NW
20     -77.033366  38.911716       NW
21     -77.033366  38.911716       NW
22     -77.033366  38.911716       NW
23     -77.033366  38.911716       NW
24     -77.033366  38.911716       NW
25     -77.033366  38.911716       NW
26     -77.033366  38.911716       NW
27     -77.033366  38.911716       NW
28     -77.033366  38.911716       NW
29     -77.033366  38.911716       NW
...           ...        ...      ...
158927 -77.019277  38.914287       NW
158928 -77.019277  38.914287       NW
158929 -77.019277  38.914287       NW
158930 -77.019245  38.912954       NW
158931 -77.019245  38.912954       NW
158932 -77.019245  38.912954       NW
158933 -77.019245  38.912954       NW
158934 -77.019245  38.912954       NW
158935 -77.019245  38.912954       NW
158936 -77.019245  38.912954       NW
158937 -77.019422  38.911848       NW
158938 -77.019422  38.911848       NW
158939 -77.019422  38.911848       NW
158940 -77.019422  38.911848       NW
158941 -77.019422  38.911848       NW
158942 -77.019422  38.911848       NW
158943 -77.019422  38.911848       NW
158944 -77.019422  38.911848       NW
158945 -77.019422  38.911848       NW
158946 -77.019422  38.911848       NW
158947 -77.019422  38.911848       NW
158948 -77.019422  38.911848       NW
158949 -77.019422  38.911848       NW
158950 -77.019422  38.911848       NW
158951 -77.019422  38.911848       NW
158952 -77.019422  38.911848       NW
158953 -77.019422  38.911848       NW
158954 -77.019422  38.911848       NW
158955 -77.018232  38.872961       SW
158956 -77.018232  38.872961       SW

[158957 rows x 49 columns]>

In [16]:
df['HF_BATHRM']

0         0
1         1
2         1
3         1
4         1
5         2
6         0
7         1
8         1
9         1
10        0
11        0
12        0
13        0
14        1
15        1
16        1
17        0
18        1
19        1
20        1
21        0
22        0
23        1
24        1
25        0
26        0
27        0
28        0
29        1
         ..
158927    0
158928    1
158929    1
158930    0
158931    1
158932    1
158933    0
158934    1
158935    0
158936    0
158937    0
158938    0
158939    0
158940    0
158941    0
158942    0
158943    1
158944    1
158945    0
158946    0
158947    0
158948    0
158949    1
158950    0
158951    1
158952    0
158953    0
158954    0
158955    0
158956    0
Name: HF_BATHRM, Length: 158957, dtype: int64

In [17]:
df['HF_BATHRM']

0         0
1         1
2         1
3         1
4         1
5         2
6         0
7         1
8         1
9         1
10        0
11        0
12        0
13        0
14        1
15        1
16        1
17        0
18        1
19        1
20        1
21        0
22        0
23        1
24        1
25        0
26        0
27        0
28        0
29        1
         ..
158927    0
158928    1
158929    1
158930    0
158931    1
158932    1
158933    0
158934    1
158935    0
158936    0
158937    0
158938    0
158939    0
158940    0
158941    0
158942    0
158943    1
158944    1
158945    0
158946    0
158947    0
158948    0
158949    1
158950    0
158951    1
158952    0
158953    0
158954    0
158955    0
158956    0
Name: HF_BATHRM, Length: 158957, dtype: int64

In [18]:
data_array.dtype

NameError: name 'data_array' is not defined

In [19]:
df.index

RangeIndex(start=0, stop=158957, step=1)

In [20]:
df.columns

Index(['Unnamed: 0', 'BATHRM', 'HF_BATHRM', 'HEAT', 'AC', 'NUM_UNITS', 'ROOMS',
       'BEDRM', 'AYB', 'YR_RMDL', 'EYB', 'STORIES', 'SALEDATE', 'PRICE',
       'QUALIFIED', 'SALE_NUM', 'GBA', 'BLDG_NUM', 'STYLE', 'STRUCT', 'GRADE',
       'CNDTN', 'EXTWALL', 'ROOF', 'INTWALL', 'KITCHENS', 'FIREPLACES',
       'USECODE', 'LANDAREA', 'GIS_LAST_MOD_DTTM', 'SOURCE', 'CMPLX_NUM',
       'LIVING_GBA', 'FULLADDRESS', 'CITY', 'STATE', 'ZIPCODE', 'NATIONALGRID',
       'LATITUDE', 'LONGITUDE', 'ASSESSMENT_NBHD', 'ASSESSMENT_SUBNBHD',
       'CENSUS_TRACT', 'CENSUS_BLOCK', 'WARD', 'SQUARE', 'X', 'Y', 'QUADRANT'],
      dtype='object')

In [22]:
mean('HF_BATHRM')

NameError: name 'mean' is not defined

In [24]:
mean['HF_BATHRM']

NameError: name 'mean' is not defined

In [25]:
df[BEDRM]

NameError: name 'BEDRM' is not defined

In [26]:
df.head

<bound method NDFrame.head of         Unnamed: 0  BATHRM  HF_BATHRM           HEAT AC  NUM_UNITS  ROOMS  \
0                0       4          0      Warm Cool  Y        2.0      8
1                1       3          1      Warm Cool  Y        2.0     11
2                2       3          1  Hot Water Rad  Y        2.0      9
3                3       3          1  Hot Water Rad  Y        2.0      8
4                4       2          1      Warm Cool  Y        1.0     11
5                5       3          2  Hot Water Rad  Y        1.0     10
6                6       1          0      Warm Cool  Y        2.0      5
7                7       3          1  Hot Water Rad  Y        2.0      8
8                8       3          1      Warm Cool  Y        2.0      7
9                9       1          1  Hot Water Rad  Y        1.0      6
10              10       3          0     Forced Air  N        3.0     12
11              11       5          0  Hot Water Rad  Y        3.0     16
12              12       2          0  Hot Water Rad  N        2.0      9
13              13       2          0      Warm Cool  Y        2.0     11
14              14       3          1      Warm Cool  Y        2.0      5
15              15       2          1      Warm Cool  Y        2.0      9
16              16       3          1      Warm Cool  Y        1.0      8
17              17       2          0  Hot Water Rad  N        1.0      6
18              18       3          1  Hot Water Rad  Y        2.0     10
19              19       3          1  Hot Water Rad  Y        2.0      9
20              20       3          1  Hot Water Rad  Y        1.0     14
21              21       3          0     Forced Air  Y        2.0     12
22              22       1          0     Forced Air  Y        1.0      6
23              23       2          1     Forced Air  Y        1.0      5
24              24       2          1  Hot Water Rad  Y        1.0      8
25              25       1          0  Hot Water Rad  N        1.0      8
26              26       1          0  Hot Water Rad  N        1.0     10
27              27       3          0  Hot Water Rad  Y        4.0      9
28              28       3          0      Warm Cool  Y        2.0     10
29              29       3          1     Forced Air  Y        2.0     11
...            ...     ...        ...            ... ..        ...    ...
158927      158927       2          0        Ht Pump  Y        NaN      6
158928      158928       2          1        Ht Pump  Y        NaN      5
158929      158929       2          1        Ht Pump  Y        NaN      5
158930      158930       2          0     Forced Air  N        NaN      4
158931      158931       2          1     Forced Air  N        NaN      4
158932      158932       2          1     Forced Air  N        NaN      4
158933      158933       2          0        Ht Pump  Y        NaN      4
158934      158934       1          1        Ht Pump  Y        NaN      3
158935      158935       1          0        Ht Pump  Y        NaN      3
158936      158936       1          0        Ht Pump  Y        NaN      3
158937      158937       1          0     Forced Air  Y        NaN      4
158938      158938       2          0      Warm Cool  Y        NaN      7
158939      158939       1          0     Forced Air  Y        NaN      4
158940      158940       2          0     Forced Air  Y        NaN      7
158941      158941       1          0     Forced Air  Y        NaN      4
158942      158942       2          0     Forced Air  Y        NaN      7
158943      158943       2          1     Forced Air  Y        NaN      5
158944      158944       2          1     Forced Air  Y        NaN      5
158945      158945       1          0     Forced Air  Y        NaN      3
158946      158946       1          0     Forced Air  Y        NaN      4
158947      158947       2          0     Forced Air  Y        NaN      4
158948      158948       2          0     Forced Air  Y        NaN      4
158949      158949       1          1     Forced Air  Y        NaN      4
158950      158950       3          0     Forced Air  Y        NaN      5
158951      158951       3          1     Forced Air  Y        NaN      5
158952      158952       1          0     Forced Air  Y        NaN      3
158953      158953       1          0     Forced Air  Y        NaN      4
158954      158954       2          0     Forced Air  Y        NaN      4
158955      158955       1          0      Warm Cool  Y        NaN      2
158956      158956       1          0      Warm Cool  Y        NaN      2

        BEDRM     AYB  YR_RMDL   ...     LONGITUDE       ASSESSMENT_NBHD  \
0           4  1910.0   1988.0   ...    -77.040832            Old City 2
1           5  1898.0   2007.0   ...    -77.040764            Old City 2
2           5  1910.0   2009.0   ...    -77.040678            Old City 2
3           5  1900.0   2003.0   ...    -77.040629            Old City 2
4           3  1913.0   2012.0   ...    -77.039361            Old City 2
5           5  1913.0      NaN   ...    -77.039715            Old City 2
6           2  1917.0   1988.0   ...    -77.041055            Old City 2
7           4  1906.0   2011.0   ...    -77.040129            Old City 2
8           3  1908.0   2008.0   ...    -77.039903            Old City 2
9           2  1908.0   1979.0   ...    -77.040081            Old City 2
10          5  1890.0   1950.0   ...    -77.040760            Old City 2
11          6  1905.0      NaN   ...    -77.039718            Old City 2
12          5  1894.0   1979.0   ...    -77.039569            Old City 2
13          5  1885.0   1979.0   ...    -77.039644            Old City 2
14          3  1917.0   2000.0   ...    -77.039716            Old City 2
15          4  1908.0   1990.0   ...    -77.039784            Old City 2
16          3  1908.0   2006.0   ...    -77.039844            Old City 2
17          3  1908.0   1987.0   ...    -77.039961            Old City 2
18          4  1908.0   2006.0   ...    -77.040020            Old City 2
19          3  1908.0   2013.0   ...    -77.040138            Old City 2
20          5  1880.0   2009.0   ...    -77.033774            Old City 2
21          3  1880.0   2009.0   ...    -77.033838            Old City 2
22          3  1880.0   2010.0   ...    -77.033925            Old City 2
23          3  1880.0   2010.0   ...    -77.033972            Old City 2
24          3  1880.0   2004.0   ...    -77.034070            Old City 2
25          4  1880.0   2010.0   ...    -77.034156            Old City 2
26          5  1900.0   2004.0   ...    -77.034258            Old City 2
27          3  1900.0   1963.0   ...    -77.034182            Old City 2
28          4  1900.0   1960.0   ...    -77.034119            Old City 2
29          3  1900.0   2014.0   ...    -77.034051            Old City 2
...       ...     ...      ...   ...           ...                   ...
158927      3  1993.0   1993.0   ...    -77.019274            Old City 2
158928      2  2013.0      NaN   ...    -77.019274            Old City 2
158929      2  2013.0      NaN   ...    -77.019274            Old City 2
158930      2  1900.0   2003.0   ...    -77.019243            Old City 2
158931      2  1900.0   2003.0   ...    -77.019243            Old City 2
158932      2  1900.0   2003.0   ...    -77.019243            Old City 2
158933      2  1880.0   2016.0   ...    -77.019243            Old City 2
158934      1  1880.0   2016.0   ...    -77.019243            Old City 2
158935      1  1880.0   2016.0   ...    -77.019243            Old City 2
158936      1  1880.0   2016.0   ...    -77.019243            Old City 2
158937      2  1992.0   1992.0   ...    -77.019420            Old City 2
158938      4  1992.0   1992.0   ...    -77.019420            Old City 2
158939      2  1992.0   1992.0   ...    -77.019420            Old City 2
158940      4  1992.0   1992.0   ...    -77.019420            Old City 2
158941      2  1992.0   1992.0   ...    -77.019420            Old City 2
158942      4  1992.0   1992.0   ...    -77.019420            Old City 2
158943      2  2004.0   2004.0   ...    -77.019420            Old City 2
158944      2  2004.0   2004.0   ...    -77.019420            Old City 2
158945      1  1938.0   2006.0   ...    -77.019420            Old City 2
158946      2  1938.0   2006.0   ...    -77.019420            Old City 2
158947      2  1938.0   2006.0   ...    -77.019420            Old City 2
158948      2  1938.0   2006.0   ...    -77.019420            Old City 2
158949      1  1938.0   2006.0   ...    -77.019420            Old City 2
158950      3  1938.0   2006.0   ...    -77.019420            Old City 2
158951      3  1938.0   2006.0   ...    -77.019420            Old City 2
158952      1  1938.0   2006.0   ...    -77.019420            Old City 2
158953      2  1938.0   2006.0   ...    -77.019420            Old City 2
158954      2  1920.0   2007.0   ...    -77.019420            Old City 2
158955      0  1965.0      NaN   ...    -77.018230  Southwest Waterfront
158956      0  1965.0      NaN   ...    -77.018230  Southwest Waterfront

       ASSESSMENT_SUBNBHD  CENSUS_TRACT CENSUS_BLOCK    WARD  SQUARE  \
0        040 D Old City 2        4201.0  004201 2006  Ward 2     152
1        040 D Old City 2        4201.0  004201 2006  Ward 2     152
2        040 D Old City 2        4201.0  004201 2006  Ward 2     152
3        040 D Old City 2        4201.0  004201 2006  Ward 2     152
4        040 D Old City 2        4201.0  004201 2006  Ward 2     152
5        040 D Old City 2        4201.0  004201 2006  Ward 2     152
6        040 D Old City 2        4201.0  004201 2005  Ward 2     152
7        040 D Old City 2        4201.0  004201 2005  Ward 2     152
8        040 D Old City 2        4201.0  004201 2005  Ward 2     152
9        040 D Old City 2        4201.0  004201 2005  Ward 2     152
10       040 D Old City 2        4201.0  004201 2005  Ward 2     152
11       040 D Old City 2        4201.0  004201 2005  Ward 2     152
12       040 D Old City 2        4201.0  004201 2005  Ward 2     152
13       040 D Old City 2        4201.0  004201 2005  Ward 2     152
14       040 D Old City 2        4201.0  004201 2005  Ward 2     152
15       040 D Old City 2        4201.0  004201 2005  Ward 2     152
16       040 D Old City 2        4201.0  004201 2005  Ward 2     152
17       040 D Old City 2        4201.0  004201 2005  Ward 2     152
18       040 D Old City 2        4201.0  004201 2005  Ward 2     152
19       040 D Old City 2        4201.0  004201 2005  Ward 2     152
20       040 E Old City 2        5201.0  005201 4003  Ward 2     208
21       040 E Old City 2        5201.0  005201 4003  Ward 2     208
22       040 E Old City 2        5201.0  005201 4003  Ward 2     208
23       040 E Old City 2        5201.0  005201 4003  Ward 2     208
24       040 E Old City 2        5201.0  005201 4003  Ward 2     208
25       040 E Old City 2        5201.0  005201 4003  Ward 2     208
26       040 E Old City 2        5201.0  005201 4003  Ward 2     208
27       040 E Old City 2        5201.0  005201 4003  Ward 2     208
28       040 E Old City 2        5201.0  005201 4003  Ward 2     208
29       040 E Old City 2        5201.0  005201 4003  Ward 2     208
...                   ...           ...          ...     ...     ...
158927   040 G Old City 2        4801.0          NaN  Ward 6     475
158928   040 G Old City 2        4801.0          NaN  Ward 6     475
158929   040 G Old City 2        4801.0          NaN  Ward 6     475
158930   040 B Old City 2        4801.0          NaN  Ward 6     476
158931   040 B Old City 2        4801.0          NaN  Ward 6     476
158932   040 B Old City 2        4801.0          NaN  Ward 6     476
158933   040 B Old City 2        4801.0          NaN  Ward 6     476
158934   040 B Old City 2        4801.0          NaN  Ward 6     476
158935   040 B Old City 2        4801.0          NaN  Ward 6     476
158936   040 B Old City 2        4801.0          NaN  Ward 6     476
158937   040 B Old City 2        4801.0          NaN  Ward 6     477
158938   040 B Old City 2        4801.0          NaN  Ward 6     477
158939   040 B Old City 2        4801.0          NaN  Ward 6     477
158940   040 B Old City 2        4801.0          NaN  Ward 6     477
158941   040 B Old City 2        4801.0          NaN  Ward 6     477
158942   040 B Old City 2        4801.0          NaN  Ward 6     477
158943   040 B Old City 2        4801.0          NaN  Ward 6     477
158944   040 B Old City 2        4801.0          NaN  Ward 6     477
158945   040 B Old City 2        4801.0          NaN  Ward 6     477
158946   040 B Old City 2        4801.0          NaN  Ward 6     477
158947   040 B Old City 2        4801.0          NaN  Ward 6     477
158948   040 B Old City 2        4801.0          NaN  Ward 6     477
158949   040 B Old City 2        4801.0          NaN  Ward 6     477
158950   040 B Old City 2        4801.0          NaN  Ward 6     477
158951   040 B Old City 2        4801.0          NaN  Ward 6     477
158952   040 B Old City 2        4801.0          NaN  Ward 6     477
158953   040 B Old City 2        4801.0          NaN  Ward 6     477
158954   040 B Old City 2        4801.0          NaN  Ward 6     477
158955                NaN       11000.0          NaN  Ward 6     504
158956                NaN       11000.0          NaN  Ward 6     504

                X          Y QUADRANT
0      -77.040429  38.914881       NW
1      -77.040429  38.914881       NW
2      -77.040429  38.914881       NW
3      -77.040429  38.914881       NW
4      -77.040429  38.914881       NW
5      -77.040429  38.914881       NW
6      -77.040429  38.914881       NW
7      -77.040429  38.914881       NW
8      -77.040429  38.914881       NW
9      -77.040429  38.914881       NW
10     -77.040429  38.914881       NW
11     -77.040429  38.914881       NW
12     -77.040429  38.914881       NW
13     -77.040429  38.914881       NW
14     -77.040429  38.914881       NW
15     -77.040429  38.914881       NW
16     -77.040429  38.914881       NW
17     -77.040429  38.914881       NW
18     -77.040429  38.914881       NW
19     -77.040429  38.914881       NW
20     -77.033366  38.911716       NW
21     -77.033366  38.911716       NW
22     -77.033366  38.911716       NW
23     -77.033366  38.911716       NW
24     -77.033366  38.911716       NW
25     -77.033366  38.911716       NW
26     -77.033366  38.911716       NW
27     -77.033366  38.911716       NW
28     -77.033366  38.911716       NW
29     -77.033366  38.911716       NW
...           ...        ...      ...
158927 -77.019277  38.914287       NW
158928 -77.019277  38.914287       NW
158929 -77.019277  38.914287       NW
158930 -77.019245  38.912954       NW
158931 -77.019245  38.912954       NW
158932 -77.019245  38.912954       NW
158933 -77.019245  38.912954       NW
158934 -77.019245  38.912954       NW
158935 -77.019245  38.912954       NW
158936 -77.019245  38.912954       NW
158937 -77.019422  38.911848       NW
158938 -77.019422  38.911848       NW
158939 -77.019422  38.911848       NW
158940 -77.019422  38.911848       NW
158941 -77.019422  38.911848       NW
158942 -77.019422  38.911848       NW
158943 -77.019422  38.911848       NW
158944 -77.019422  38.911848       NW
158945 -77.019422  38.911848       NW
158946 -77.019422  38.911848       NW
158947 -77.019422  38.911848       NW
158948 -77.019422  38.911848       NW
158949 -77.019422  38.911848       NW
158950 -77.019422  38.911848       NW
158951 -77.019422  38.911848       NW
158952 -77.019422  38.911848       NW
158953 -77.019422  38.911848       NW
158954 -77.019422  38.911848       NW
158955 -77.018232  38.872961       SW
158956 -77.018232  38.872961       SW

[158957 rows x 49 columns]>

In [27]:
df(LONGITUDE)

NameError: name 'LONGITUDE' is not defined

In [28]:
df(Unnamed)

NameError: name 'Unnamed' is not defined

In [29]:
df.columns

Index(['Unnamed: 0', 'BATHRM', 'HF_BATHRM', 'HEAT', 'AC', 'NUM_UNITS', 'ROOMS',
       'BEDRM', 'AYB', 'YR_RMDL', 'EYB', 'STORIES', 'SALEDATE', 'PRICE',
       'QUALIFIED', 'SALE_NUM', 'GBA', 'BLDG_NUM', 'STYLE', 'STRUCT', 'GRADE',
       'CNDTN', 'EXTWALL', 'ROOF', 'INTWALL', 'KITCHENS', 'FIREPLACES',
       'USECODE', 'LANDAREA', 'GIS_LAST_MOD_DTTM', 'SOURCE', 'CMPLX_NUM',
       'LIVING_GBA', 'FULLADDRESS', 'CITY', 'STATE', 'ZIPCODE', 'NATIONALGRID',
       'LATITUDE', 'LONGITUDE', 'ASSESSMENT_NBHD', 'ASSESSMENT_SUBNBHD',
       'CENSUS_TRACT', 'CENSUS_BLOCK', 'WARD', 'SQUARE', 'X', 'Y', 'QUADRANT'],
      dtype='object')

In [30]:
df.head

<bound method NDFrame.head of         Unnamed: 0  BATHRM  HF_BATHRM           HEAT AC  NUM_UNITS  ROOMS  \
0                0       4          0      Warm Cool  Y        2.0      8
1                1       3          1      Warm Cool  Y        2.0     11
2                2       3          1  Hot Water Rad  Y        2.0      9
3                3       3          1  Hot Water Rad  Y        2.0      8
4                4       2          1      Warm Cool  Y        1.0     11
5                5       3          2  Hot Water Rad  Y        1.0     10
6                6       1          0      Warm Cool  Y        2.0      5
7                7       3          1  Hot Water Rad  Y        2.0      8
8                8       3          1      Warm Cool  Y        2.0      7
9                9       1          1  Hot Water Rad  Y        1.0      6
10              10       3          0     Forced Air  N        3.0     12
11              11       5          0  Hot Water Rad  Y        3.0     16
12              12       2          0  Hot Water Rad  N        2.0      9
13              13       2          0      Warm Cool  Y        2.0     11
14              14       3          1      Warm Cool  Y        2.0      5
15              15       2          1      Warm Cool  Y        2.0      9
16              16       3          1      Warm Cool  Y        1.0      8
17              17       2          0  Hot Water Rad  N        1.0      6
18              18       3          1  Hot Water Rad  Y        2.0     10
19              19       3          1  Hot Water Rad  Y        2.0      9
20              20       3          1  Hot Water Rad  Y        1.0     14
21              21       3          0     Forced Air  Y        2.0     12
22              22       1          0     Forced Air  Y        1.0      6
23              23       2          1     Forced Air  Y        1.0      5
24              24       2          1  Hot Water Rad  Y        1.0      8
25              25       1          0  Hot Water Rad  N        1.0      8
26              26       1          0  Hot Water Rad  N        1.0     10
27              27       3          0  Hot Water Rad  Y        4.0      9
28              28       3          0      Warm Cool  Y        2.0     10
29              29       3          1     Forced Air  Y        2.0     11
...            ...     ...        ...            ... ..        ...    ...
158927      158927       2          0        Ht Pump  Y        NaN      6
158928      158928       2          1        Ht Pump  Y        NaN      5
158929      158929       2          1        Ht Pump  Y        NaN      5
158930      158930       2          0     Forced Air  N        NaN      4
158931      158931       2          1     Forced Air  N        NaN      4
158932      158932       2          1     Forced Air  N        NaN      4
158933      158933       2          0        Ht Pump  Y        NaN      4
158934      158934       1          1        Ht Pump  Y        NaN      3
158935      158935       1          0        Ht Pump  Y        NaN      3
158936      158936       1          0        Ht Pump  Y        NaN      3
158937      158937       1          0     Forced Air  Y        NaN      4
158938      158938       2          0      Warm Cool  Y        NaN      7
158939      158939       1          0     Forced Air  Y        NaN      4
158940      158940       2          0     Forced Air  Y        NaN      7
158941      158941       1          0     Forced Air  Y        NaN      4
158942      158942       2          0     Forced Air  Y        NaN      7
158943      158943       2          1     Forced Air  Y        NaN      5
158944      158944       2          1     Forced Air  Y        NaN      5
158945      158945       1          0     Forced Air  Y        NaN      3
158946      158946       1          0     Forced Air  Y        NaN      4
158947      158947       2          0     Forced Air  Y        NaN      4
158948      158948       2          0     Forced Air  Y        NaN      4
158949      158949       1          1     Forced Air  Y        NaN      4
158950      158950       3          0     Forced Air  Y        NaN      5
158951      158951       3          1     Forced Air  Y        NaN      5
158952      158952       1          0     Forced Air  Y        NaN      3
158953      158953       1          0     Forced Air  Y        NaN      4
158954      158954       2          0     Forced Air  Y        NaN      4
158955      158955       1          0      Warm Cool  Y        NaN      2
158956      158956       1          0      Warm Cool  Y        NaN      2

        BEDRM     AYB  YR_RMDL   ...     LONGITUDE       ASSESSMENT_NBHD  \
0           4  1910.0   1988.0   ...    -77.040832            Old City 2
1           5  1898.0   2007.0   ...    -77.040764            Old City 2
2           5  1910.0   2009.0   ...    -77.040678            Old City 2
3           5  1900.0   2003.0   ...    -77.040629            Old City 2
4           3  1913.0   2012.0   ...    -77.039361            Old City 2
5           5  1913.0      NaN   ...    -77.039715            Old City 2
6           2  1917.0   1988.0   ...    -77.041055            Old City 2
7           4  1906.0   2011.0   ...    -77.040129            Old City 2
8           3  1908.0   2008.0   ...    -77.039903            Old City 2
9           2  1908.0   1979.0   ...    -77.040081            Old City 2
10          5  1890.0   1950.0   ...    -77.040760            Old City 2
11          6  1905.0      NaN   ...    -77.039718            Old City 2
12          5  1894.0   1979.0   ...    -77.039569            Old City 2
13          5  1885.0   1979.0   ...    -77.039644            Old City 2
14          3  1917.0   2000.0   ...    -77.039716            Old City 2
15          4  1908.0   1990.0   ...    -77.039784            Old City 2
16          3  1908.0   2006.0   ...    -77.039844            Old City 2
17          3  1908.0   1987.0   ...    -77.039961            Old City 2
18          4  1908.0   2006.0   ...    -77.040020            Old City 2
19          3  1908.0   2013.0   ...    -77.040138            Old City 2
20          5  1880.0   2009.0   ...    -77.033774            Old City 2
21          3  1880.0   2009.0   ...    -77.033838            Old City 2
22          3  1880.0   2010.0   ...    -77.033925            Old City 2
23          3  1880.0   2010.0   ...    -77.033972            Old City 2
24          3  1880.0   2004.0   ...    -77.034070            Old City 2
25          4  1880.0   2010.0   ...    -77.034156            Old City 2
26          5  1900.0   2004.0   ...    -77.034258            Old City 2
27          3  1900.0   1963.0   ...    -77.034182            Old City 2
28          4  1900.0   1960.0   ...    -77.034119            Old City 2
29          3  1900.0   2014.0   ...    -77.034051            Old City 2
...       ...     ...      ...   ...           ...                   ...
158927      3  1993.0   1993.0   ...    -77.019274            Old City 2
158928      2  2013.0      NaN   ...    -77.019274            Old City 2
158929      2  2013.0      NaN   ...    -77.019274            Old City 2
158930      2  1900.0   2003.0   ...    -77.019243            Old City 2
158931      2  1900.0   2003.0   ...    -77.019243            Old City 2
158932      2  1900.0   2003.0   ...    -77.019243            Old City 2
158933      2  1880.0   2016.0   ...    -77.019243            Old City 2
158934      1  1880.0   2016.0   ...    -77.019243            Old City 2
158935      1  1880.0   2016.0   ...    -77.019243            Old City 2
158936      1  1880.0   2016.0   ...    -77.019243            Old City 2
158937      2  1992.0   1992.0   ...    -77.019420            Old City 2
158938      4  1992.0   1992.0   ...    -77.019420            Old City 2
158939      2  1992.0   1992.0   ...    -77.019420            Old City 2
158940      4  1992.0   1992.0   ...    -77.019420            Old City 2
158941      2  1992.0   1992.0   ...    -77.019420            Old City 2
158942      4  1992.0   1992.0   ...    -77.019420            Old City 2
158943      2  2004.0   2004.0   ...    -77.019420            Old City 2
158944      2  2004.0   2004.0   ...    -77.019420            Old City 2
158945      1  1938.0   2006.0   ...    -77.019420            Old City 2
158946      2  1938.0   2006.0   ...    -77.019420            Old City 2
158947      2  1938.0   2006.0   ...    -77.019420            Old City 2
158948      2  1938.0   2006.0   ...    -77.019420            Old City 2
158949      1  1938.0   2006.0   ...    -77.019420            Old City 2
158950      3  1938.0   2006.0   ...    -77.019420            Old City 2
158951      3  1938.0   2006.0   ...    -77.019420            Old City 2
158952      1  1938.0   2006.0   ...    -77.019420            Old City 2
158953      2  1938.0   2006.0   ...    -77.019420            Old City 2
158954      2  1920.0   2007.0   ...    -77.019420            Old City 2
158955      0  1965.0      NaN   ...    -77.018230  Southwest Waterfront
158956      0  1965.0      NaN   ...    -77.018230  Southwest Waterfront

       ASSESSMENT_SUBNBHD  CENSUS_TRACT CENSUS_BLOCK    WARD  SQUARE  \
0        040 D Old City 2        4201.0  004201 2006  Ward 2     152
1        040 D Old City 2        4201.0  004201 2006  Ward 2     152
2        040 D Old City 2        4201.0  004201 2006  Ward 2     152
3        040 D Old City 2        4201.0  004201 2006  Ward 2     152
4        040 D Old City 2        4201.0  004201 2006  Ward 2     152
5        040 D Old City 2        4201.0  004201 2006  Ward 2     152
6        040 D Old City 2        4201.0  004201 2005  Ward 2     152
7        040 D Old City 2        4201.0  004201 2005  Ward 2     152
8        040 D Old City 2        4201.0  004201 2005  Ward 2     152
9        040 D Old City 2        4201.0  004201 2005  Ward 2     152
10       040 D Old City 2        4201.0  004201 2005  Ward 2     152
11       040 D Old City 2        4201.0  004201 2005  Ward 2     152
12       040 D Old City 2        4201.0  004201 2005  Ward 2     152
13       040 D Old City 2        4201.0  004201 2005  Ward 2     152
14       040 D Old City 2        4201.0  004201 2005  Ward 2     152
15       040 D Old City 2        4201.0  004201 2005  Ward 2     152
16       040 D Old City 2        4201.0  004201 2005  Ward 2     152
17       040 D Old City 2        4201.0  004201 2005  Ward 2     152
18       040 D Old City 2        4201.0  004201 2005  Ward 2     152
19       040 D Old City 2        4201.0  004201 2005  Ward 2     152
20       040 E Old City 2        5201.0  005201 4003  Ward 2     208
21       040 E Old City 2        5201.0  005201 4003  Ward 2     208
22       040 E Old City 2        5201.0  005201 4003  Ward 2     208
23       040 E Old City 2        5201.0  005201 4003  Ward 2     208
24       040 E Old City 2        5201.0  005201 4003  Ward 2     208
25       040 E Old City 2        5201.0  005201 4003  Ward 2     208
26       040 E Old City 2        5201.0  005201 4003  Ward 2     208
27       040 E Old City 2        5201.0  005201 4003  Ward 2     208
28       040 E Old City 2        5201.0  005201 4003  Ward 2     208
29       040 E Old City 2        5201.0  005201 4003  Ward 2     208
...                   ...           ...          ...     ...     ...
158927   040 G Old City 2        4801.0          NaN  Ward 6     475
158928   040 G Old City 2        4801.0          NaN  Ward 6     475
158929   040 G Old City 2        4801.0          NaN  Ward 6     475
158930   040 B Old City 2        4801.0          NaN  Ward 6     476
158931   040 B Old City 2        4801.0          NaN  Ward 6     476
158932   040 B Old City 2        4801.0          NaN  Ward 6     476
158933   040 B Old City 2        4801.0          NaN  Ward 6     476
158934   040 B Old City 2        4801.0          NaN  Ward 6     476
158935   040 B Old City 2        4801.0          NaN  Ward 6     476
158936   040 B Old City 2        4801.0          NaN  Ward 6     476
158937   040 B Old City 2        4801.0          NaN  Ward 6     477
158938   040 B Old City 2        4801.0          NaN  Ward 6     477
158939   040 B Old City 2        4801.0          NaN  Ward 6     477
158940   040 B Old City 2        4801.0          NaN  Ward 6     477
158941   040 B Old City 2        4801.0          NaN  Ward 6     477
158942   040 B Old City 2        4801.0          NaN  Ward 6     477
158943   040 B Old City 2        4801.0          NaN  Ward 6     477
158944   040 B Old City 2        4801.0          NaN  Ward 6     477
158945   040 B Old City 2        4801.0          NaN  Ward 6     477
158946   040 B Old City 2        4801.0          NaN  Ward 6     477
158947   040 B Old City 2        4801.0          NaN  Ward 6     477
158948   040 B Old City 2        4801.0          NaN  Ward 6     477
158949   040 B Old City 2        4801.0          NaN  Ward 6     477
158950   040 B Old City 2        4801.0          NaN  Ward 6     477
158951   040 B Old City 2        4801.0          NaN  Ward 6     477
158952   040 B Old City 2        4801.0          NaN  Ward 6     477
158953   040 B Old City 2        4801.0          NaN  Ward 6     477
158954   040 B Old City 2        4801.0          NaN  Ward 6     477
158955                NaN       11000.0          NaN  Ward 6     504
158956                NaN       11000.0          NaN  Ward 6     504

                X          Y QUADRANT
0      -77.040429  38.914881       NW
1      -77.040429  38.914881       NW
2      -77.040429  38.914881       NW
3      -77.040429  38.914881       NW
4      -77.040429  38.914881       NW
5      -77.040429  38.914881       NW
6      -77.040429  38.914881       NW
7      -77.040429  38.914881       NW
8      -77.040429  38.914881       NW
9      -77.040429  38.914881       NW
10     -77.040429  38.914881       NW
11     -77.040429  38.914881       NW
12     -77.040429  38.914881       NW
13     -77.040429  38.914881       NW
14     -77.040429  38.914881       NW
15     -77.040429  38.914881       NW
16     -77.040429  38.914881       NW
17     -77.040429  38.914881       NW
18     -77.040429  38.914881       NW
19     -77.040429  38.914881       NW
20     -77.033366  38.911716       NW
21     -77.033366  38.911716       NW
22     -77.033366  38.911716       NW
23     -77.033366  38.911716       NW
24     -77.033366  38.911716       NW
25     -77.033366  38.911716       NW
26     -77.033366  38.911716       NW
27     -77.033366  38.911716       NW
28     -77.033366  38.911716       NW
29     -77.033366  38.911716       NW
...           ...        ...      ...
158927 -77.019277  38.914287       NW
158928 -77.019277  38.914287       NW
158929 -77.019277  38.914287       NW
158930 -77.019245  38.912954       NW
158931 -77.019245  38.912954       NW
158932 -77.019245  38.912954       NW
158933 -77.019245  38.912954       NW
158934 -77.019245  38.912954       NW
158935 -77.019245  38.912954       NW
158936 -77.019245  38.912954       NW
158937 -77.019422  38.911848       NW
158938 -77.019422  38.911848       NW
158939 -77.019422  38.911848       NW
158940 -77.019422  38.911848       NW
158941 -77.019422  38.911848       NW
158942 -77.019422  38.911848       NW
158943 -77.019422  38.911848       NW
158944 -77.019422  38.911848       NW
158945 -77.019422  38.911848       NW
158946 -77.019422  38.911848       NW
158947 -77.019422  38.911848       NW
158948 -77.019422  38.911848       NW
158949 -77.019422  38.911848       NW
158950 -77.019422  38.911848       NW
158951 -77.019422  38.911848       NW
158952 -77.019422  38.911848       NW
158953 -77.019422  38.911848       NW
158954 -77.019422  38.911848       NW
158955 -77.018232  38.872961       SW
158956 -77.018232  38.872961       SW

[158957 rows x 49 columns]>

In [31]:
df(HF_BATHRM).max()

NameError: name 'HF_BATHRM' is not defined

In [32]:
df('HF_BATHRM').max()

TypeError: 'DataFrame' object is not callable

In [33]:
df.count

<bound method DataFrame.count of         Unnamed: 0  BATHRM  HF_BATHRM           HEAT AC  NUM_UNITS  ROOMS  \
0                0       4          0      Warm Cool  Y        2.0      8
1                1       3          1      Warm Cool  Y        2.0     11
2                2       3          1  Hot Water Rad  Y        2.0      9
3                3       3          1  Hot Water Rad  Y        2.0      8
4                4       2          1      Warm Cool  Y        1.0     11
5                5       3          2  Hot Water Rad  Y        1.0     10
6                6       1          0      Warm Cool  Y        2.0      5
7                7       3          1  Hot Water Rad  Y        2.0      8
8                8       3          1      Warm Cool  Y        2.0      7
9                9       1          1  Hot Water Rad  Y        1.0      6
10              10       3          0     Forced Air  N        3.0     12
11              11       5          0  Hot Water Rad  Y        3.0     16
12              12       2          0  Hot Water Rad  N        2.0      9
13              13       2          0      Warm Cool  Y        2.0     11
14              14       3          1      Warm Cool  Y        2.0      5
15              15       2          1      Warm Cool  Y        2.0      9
16              16       3          1      Warm Cool  Y        1.0      8
17              17       2          0  Hot Water Rad  N        1.0      6
18              18       3          1  Hot Water Rad  Y        2.0     10
19              19       3          1  Hot Water Rad  Y        2.0      9
20              20       3          1  Hot Water Rad  Y        1.0     14
21              21       3          0     Forced Air  Y        2.0     12
22              22       1          0     Forced Air  Y        1.0      6
23              23       2          1     Forced Air  Y        1.0      5
24              24       2          1  Hot Water Rad  Y        1.0      8
25              25       1          0  Hot Water Rad  N        1.0      8
26              26       1          0  Hot Water Rad  N        1.0     10
27              27       3          0  Hot Water Rad  Y        4.0      9
28              28       3          0      Warm Cool  Y        2.0     10
29              29       3          1     Forced Air  Y        2.0     11
...            ...     ...        ...            ... ..        ...    ...
158927      158927       2          0        Ht Pump  Y        NaN      6
158928      158928       2          1        Ht Pump  Y        NaN      5
158929      158929       2          1        Ht Pump  Y        NaN      5
158930      158930       2          0     Forced Air  N        NaN      4
158931      158931       2          1     Forced Air  N        NaN      4
158932      158932       2          1     Forced Air  N        NaN      4
158933      158933       2          0        Ht Pump  Y        NaN      4
158934      158934       1          1        Ht Pump  Y        NaN      3
158935      158935       1          0        Ht Pump  Y        NaN      3
158936      158936       1          0        Ht Pump  Y        NaN      3
158937      158937       1          0     Forced Air  Y        NaN      4
158938      158938       2          0      Warm Cool  Y        NaN      7
158939      158939       1          0     Forced Air  Y        NaN      4
158940      158940       2          0     Forced Air  Y        NaN      7
158941      158941       1          0     Forced Air  Y        NaN      4
158942      158942       2          0     Forced Air  Y        NaN      7
158943      158943       2          1     Forced Air  Y        NaN      5
158944      158944       2          1     Forced Air  Y        NaN      5
158945      158945       1          0     Forced Air  Y        NaN      3
158946      158946       1          0     Forced Air  Y        NaN      4
158947      158947       2          0     Forced Air  Y        NaN      4
158948      158948       2          0     Forced Air  Y        NaN      4
158949      158949       1          1     Forced Air  Y        NaN      4
158950      158950       3          0     Forced Air  Y        NaN      5
158951      158951       3          1     Forced Air  Y        NaN      5
158952      158952       1          0     Forced Air  Y        NaN      3
158953      158953       1          0     Forced Air  Y        NaN      4
158954      158954       2          0     Forced Air  Y        NaN      4
158955      158955       1          0      Warm Cool  Y        NaN      2
158956      158956       1          0      Warm Cool  Y        NaN      2

        BEDRM     AYB  YR_RMDL   ...     LONGITUDE       ASSESSMENT_NBHD  \
0           4  1910.0   1988.0   ...    -77.040832            Old City 2
1           5  1898.0   2007.0   ...    -77.040764            Old City 2
2           5  1910.0   2009.0   ...    -77.040678            Old City 2
3           5  1900.0   2003.0   ...    -77.040629            Old City 2
4           3  1913.0   2012.0   ...    -77.039361            Old City 2
5           5  1913.0      NaN   ...    -77.039715            Old City 2
6           2  1917.0   1988.0   ...    -77.041055            Old City 2
7           4  1906.0   2011.0   ...    -77.040129            Old City 2
8           3  1908.0   2008.0   ...    -77.039903            Old City 2
9           2  1908.0   1979.0   ...    -77.040081            Old City 2
10          5  1890.0   1950.0   ...    -77.040760            Old City 2
11          6  1905.0      NaN   ...    -77.039718            Old City 2
12          5  1894.0   1979.0   ...    -77.039569            Old City 2
13          5  1885.0   1979.0   ...    -77.039644            Old City 2
14          3  1917.0   2000.0   ...    -77.039716            Old City 2
15          4  1908.0   1990.0   ...    -77.039784            Old City 2
16          3  1908.0   2006.0   ...    -77.039844            Old City 2
17          3  1908.0   1987.0   ...    -77.039961            Old City 2
18          4  1908.0   2006.0   ...    -77.040020            Old City 2
19          3  1908.0   2013.0   ...    -77.040138            Old City 2
20          5  1880.0   2009.0   ...    -77.033774            Old City 2
21          3  1880.0   2009.0   ...    -77.033838            Old City 2
22          3  1880.0   2010.0   ...    -77.033925            Old City 2
23          3  1880.0   2010.0   ...    -77.033972            Old City 2
24          3  1880.0   2004.0   ...    -77.034070            Old City 2
25          4  1880.0   2010.0   ...    -77.034156            Old City 2
26          5  1900.0   2004.0   ...    -77.034258            Old City 2
27          3  1900.0   1963.0   ...    -77.034182            Old City 2
28          4  1900.0   1960.0   ...    -77.034119            Old City 2
29          3  1900.0   2014.0   ...    -77.034051            Old City 2
...       ...     ...      ...   ...           ...                   ...
158927      3  1993.0   1993.0   ...    -77.019274            Old City 2
158928      2  2013.0      NaN   ...    -77.019274            Old City 2
158929      2  2013.0      NaN   ...    -77.019274            Old City 2
158930      2  1900.0   2003.0   ...    -77.019243            Old City 2
158931      2  1900.0   2003.0   ...    -77.019243            Old City 2
158932      2  1900.0   2003.0   ...    -77.019243            Old City 2
158933      2  1880.0   2016.0   ...    -77.019243            Old City 2
158934      1  1880.0   2016.0   ...    -77.019243            Old City 2
158935      1  1880.0   2016.0   ...    -77.019243            Old City 2
158936      1  1880.0   2016.0   ...    -77.019243            Old City 2
158937      2  1992.0   1992.0   ...    -77.019420            Old City 2
158938      4  1992.0   1992.0   ...    -77.019420            Old City 2
158939      2  1992.0   1992.0   ...    -77.019420            Old City 2
158940      4  1992.0   1992.0   ...    -77.019420            Old City 2
158941      2  1992.0   1992.0   ...    -77.019420            Old City 2
158942      4  1992.0   1992.0   ...    -77.019420            Old City 2
158943      2  2004.0   2004.0   ...    -77.019420            Old City 2
158944      2  2004.0   2004.0   ...    -77.019420            Old City 2
158945      1  1938.0   2006.0   ...    -77.019420            Old City 2
158946      2  1938.0   2006.0   ...    -77.019420            Old City 2
158947      2  1938.0   2006.0   ...    -77.019420            Old City 2
158948      2  1938.0   2006.0   ...    -77.019420            Old City 2
158949      1  1938.0   2006.0   ...    -77.019420            Old City 2
158950      3  1938.0   2006.0   ...    -77.019420            Old City 2
158951      3  1938.0   2006.0   ...    -77.019420            Old City 2
158952      1  1938.0   2006.0   ...    -77.019420            Old City 2
158953      2  1938.0   2006.0   ...    -77.019420            Old City 2
158954      2  1920.0   2007.0   ...    -77.019420            Old City 2
158955      0  1965.0      NaN   ...    -77.018230  Southwest Waterfront
158956      0  1965.0      NaN   ...    -77.018230  Southwest Waterfront

       ASSESSMENT_SUBNBHD  CENSUS_TRACT CENSUS_BLOCK    WARD  SQUARE  \
0        040 D Old City 2        4201.0  004201 2006  Ward 2     152
1        040 D Old City 2        4201.0  004201 2006  Ward 2     152
2        040 D Old City 2        4201.0  004201 2006  Ward 2     152
3        040 D Old City 2        4201.0  004201 2006  Ward 2     152
4        040 D Old City 2        4201.0  004201 2006  Ward 2     152
5        040 D Old City 2        4201.0  004201 2006  Ward 2     152
6        040 D Old City 2        4201.0  004201 2005  Ward 2     152
7        040 D Old City 2        4201.0  004201 2005  Ward 2     152
8        040 D Old City 2        4201.0  004201 2005  Ward 2     152
9        040 D Old City 2        4201.0  004201 2005  Ward 2     152
10       040 D Old City 2        4201.0  004201 2005  Ward 2     152
11       040 D Old City 2        4201.0  004201 2005  Ward 2     152
12       040 D Old City 2        4201.0  004201 2005  Ward 2     152
13       040 D Old City 2        4201.0  004201 2005  Ward 2     152
14       040 D Old City 2        4201.0  004201 2005  Ward 2     152
15       040 D Old City 2        4201.0  004201 2005  Ward 2     152
16       040 D Old City 2        4201.0  004201 2005  Ward 2     152
17       040 D Old City 2        4201.0  004201 2005  Ward 2     152
18       040 D Old City 2        4201.0  004201 2005  Ward 2     152
19       040 D Old City 2        4201.0  004201 2005  Ward 2     152
20       040 E Old City 2        5201.0  005201 4003  Ward 2     208
21       040 E Old City 2        5201.0  005201 4003  Ward 2     208
22       040 E Old City 2        5201.0  005201 4003  Ward 2     208
23       040 E Old City 2        5201.0  005201 4003  Ward 2     208
24       040 E Old City 2        5201.0  005201 4003  Ward 2     208
25       040 E Old City 2        5201.0  005201 4003  Ward 2     208
26       040 E Old City 2        5201.0  005201 4003  Ward 2     208
27       040 E Old City 2        5201.0  005201 4003  Ward 2     208
28       040 E Old City 2        5201.0  005201 4003  Ward 2     208
29       040 E Old City 2        5201.0  005201 4003  Ward 2     208
...                   ...           ...          ...     ...     ...
158927   040 G Old City 2        4801.0          NaN  Ward 6     475
158928   040 G Old City 2        4801.0          NaN  Ward 6     475
158929   040 G Old City 2        4801.0          NaN  Ward 6     475
158930   040 B Old City 2        4801.0          NaN  Ward 6     476
158931   040 B Old City 2        4801.0          NaN  Ward 6     476
158932   040 B Old City 2        4801.0          NaN  Ward 6     476
158933   040 B Old City 2        4801.0          NaN  Ward 6     476
158934   040 B Old City 2        4801.0          NaN  Ward 6     476
158935   040 B Old City 2        4801.0          NaN  Ward 6     476
158936   040 B Old City 2        4801.0          NaN  Ward 6     476
158937   040 B Old City 2        4801.0          NaN  Ward 6     477
158938   040 B Old City 2        4801.0          NaN  Ward 6     477
158939   040 B Old City 2        4801.0          NaN  Ward 6     477
158940   040 B Old City 2        4801.0          NaN  Ward 6     477
158941   040 B Old City 2        4801.0          NaN  Ward 6     477
158942   040 B Old City 2        4801.0          NaN  Ward 6     477
158943   040 B Old City 2        4801.0          NaN  Ward 6     477
158944   040 B Old City 2        4801.0          NaN  Ward 6     477
158945   040 B Old City 2        4801.0          NaN  Ward 6     477
158946   040 B Old City 2        4801.0          NaN  Ward 6     477
158947   040 B Old City 2        4801.0          NaN  Ward 6     477
158948   040 B Old City 2        4801.0          NaN  Ward 6     477
158949   040 B Old City 2        4801.0          NaN  Ward 6     477
158950   040 B Old City 2        4801.0          NaN  Ward 6     477
158951   040 B Old City 2        4801.0          NaN  Ward 6     477
158952   040 B Old City 2        4801.0          NaN  Ward 6     477
158953   040 B Old City 2        4801.0          NaN  Ward 6     477
158954   040 B Old City 2        4801.0          NaN  Ward 6     477
158955                NaN       11000.0          NaN  Ward 6     504
158956                NaN       11000.0          NaN  Ward 6     504

                X          Y QUADRANT
0      -77.040429  38.914881       NW
1      -77.040429  38.914881       NW
2      -77.040429  38.914881       NW
3      -77.040429  38.914881       NW
4      -77.040429  38.914881       NW
5      -77.040429  38.914881       NW
6      -77.040429  38.914881       NW
7      -77.040429  38.914881       NW
8      -77.040429  38.914881       NW
9      -77.040429  38.914881       NW
10     -77.040429  38.914881       NW
11     -77.040429  38.914881       NW
12     -77.040429  38.914881       NW
13     -77.040429  38.914881       NW
14     -77.040429  38.914881       NW
15     -77.040429  38.914881       NW
16     -77.040429  38.914881       NW
17     -77.040429  38.914881       NW
18     -77.040429  38.914881       NW
19     -77.040429  38.914881       NW
20     -77.033366  38.911716       NW
21     -77.033366  38.911716       NW
22     -77.033366  38.911716       NW
23     -77.033366  38.911716       NW
24     -77.033366  38.911716       NW
25     -77.033366  38.911716       NW
26     -77.033366  38.911716       NW
27     -77.033366  38.911716       NW
28     -77.033366  38.911716       NW
29     -77.033366  38.911716       NW
...           ...        ...      ...
158927 -77.019277  38.914287       NW
158928 -77.019277  38.914287       NW
158929 -77.019277  38.914287       NW
158930 -77.019245  38.912954       NW
158931 -77.019245  38.912954       NW
158932 -77.019245  38.912954       NW
158933 -77.019245  38.912954       NW
158934 -77.019245  38.912954       NW
158935 -77.019245  38.912954       NW
158936 -77.019245  38.912954       NW
158937 -77.019422  38.911848       NW
158938 -77.019422  38.911848       NW
158939 -77.019422  38.911848       NW
158940 -77.019422  38.911848       NW
158941 -77.019422  38.911848       NW
158942 -77.019422  38.911848       NW
158943 -77.019422  38.911848       NW
158944 -77.019422  38.911848       NW
158945 -77.019422  38.911848       NW
158946 -77.019422  38.911848       NW
158947 -77.019422  38.911848       NW
158948 -77.019422  38.911848       NW
158949 -77.019422  38.911848       NW
158950 -77.019422  38.911848       NW
158951 -77.019422  38.911848       NW
158952 -77.019422  38.911848       NW
158953 -77.019422  38.911848       NW
158954 -77.019422  38.911848       NW
158955 -77.018232  38.872961       SW
158956 -77.018232  38.872961       SW

[158957 rows x 49 columns]>

In [35]:
df['DC_Properties.csv'].max()

KeyError: 'DC_Properties.csv'

In [36]:
df['BEDRM'].max()

24

In [37]:
df['BEDRM'].min()

0

In [38]:
df['BEDRM'].min()

0

In [39]:
df['BEDRM'].sum()

434351

In [40]:
df['BEDRM'].mean()

2.7325062752819944

In [41]:
df['BEDRM'].median()

3.0

In [42]:
df['BEDRM'].mode()

0    3
dtype: int64

In [43]:
df['BEDRM'].value_counts()

3     57864
2     34946
4     24893
1     24181
5      6898
0      5297
6      3090
8       792
7       750
9       123
10       62
12       34
11       13
13        4
15        3
14        2
16        2
20        1
19        1
24        1
Name: BEDRM, dtype: int64

In [44]:
df['BEDRM'].std()

1.3588642440202134

In [45]:
 df['ASSESSMENT_SUBNBHD'].max() df['BEDRM'].value_counts()

TypeError: '>=' not supported between instances of 'str' and 'float'

In [46]:
 df['ASSESSMENT_SUBNBHD'].value_counts()

040 D Old City 2             4403
040 E Old City 2             2968
040 C Old City 2             2886
042 B Petworth               2763
039 K Old City 1             2640
007 E Brookland              2388
040 B Old City 2             2289
015 D Columbia Heights       2246
015 A Columbia Heights       2206
015 E Columbia Heights       2183
016 B Congress Heights       2120
042 C Petworth               2017
039 L Old City 1             1908
028 C Hillcrest              1881
011 A Chevy Chase            1823
018 C Deanwood               1783
036 A Mt. Pleasant           1762
039 F Old City 1             1717
016 C Congress Heights       1633
007 C Brookland              1631
018 B Deanwood               1613
054 B Wesley Heights         1570
015 C Columbia Heights       1561
018 A Deanwood               1552
033 A Marshall Heights       1549
042 A Petworth               1543
039 A Old City 1             1538
040 F Old City 2             1499
019 B Eckington              1435
009 B Capitol Hill           1381
                             ...
025 F Georgetown              533
056 B Woodridge               519
025 J Georgetown              504
025 E Georgetown              475
050 B Spring Valley           452
039 D Old City 1              424
022 A Fort Dupont Park        421
025 D Georgetown              420
054 A Wesley Heights          411
001 A American University     401
004 A Berkley                 393
032 A Lily Ponds              392
030 B Kent                    356
041 A Palisades               329
030 C Kent                    314
005 B Brentwood               282
056 D Woodridge               273
018 D Deanwood                270
008 B Burleith                267
025 G Georgetown              262
004 B Berkley                 228
033 B Marshall Heights        204
030 A Kent                    197
025 B Georgetown              182
050 C Spring Valley           178
050 A Spring Valley           176
004 C Berkley                 154
025 A Georgetown              140
050 D Spring Valley           131
025 C Georgetown               91
Name: ASSESSMENT_SUBNBHD, Length: 121, dtype: int64

In [48]:
 df['ASSESSMENT_SUBNBHD'].mean()

TypeError: can only concatenate str (not "int") to str

In [49]:
 df.describe['ASSESSMENT_SUBNBHD']

TypeError: 'method' object is not subscriptable

In [50]:
df['AYB'],max()

TypeError: max expected 1 arguments, got 0

In [51]:
df['AYB'].max()

2019.0

In [52]:
df['AYB'].min()

1754.0

In [53]:
df['AYB'].sum()

308166241.0

In [54]:
df['AYB'].median()

1937.0

In [55]:
df['AYB'].mode()

0    1900.0
dtype: float64

In [56]:
df['AYB'].value_counts()

1900.0    8967
1925.0    5129
1910.0    4563
1940.0    4316
1923.0    3724
1927.0    3707
1941.0    3420
1926.0    3117
1942.0    3058
1939.0    2849
1950.0    2696
1937.0    2690
1936.0    2553
2007.0    2291
1908.0    2274
1912.0    2272
1938.0    2246
1928.0    2190
1909.0    2154
2005.0    2146
1951.0    2086
1947.0    2058
1920.0    2019
2006.0    2019
1890.0    1976
1930.0    1884
1929.0    1838
1960.0    1816
1948.0    1808
1911.0    1807
          ...
1819.0       2
1835.0       2
1861.0       2
1847.0       2
1849.0       2
1824.0       2
1808.0       1
1793.0       1
1765.0       1
1866.0       1
1782.0       1
1784.0       1
1785.0       1
1787.0       1
1788.0       1
1854.0       1
1791.0       1
1851.0       1
1834.0       1
1795.0       1
1822.0       1
1797.0       1
1799.0       1
1833.0       1
1846.0       1
1844.0       1
1842.0       1
1841.0       1
1806.0       1
2019.0       1
Name: AYB, Length: 220, dtype: int64

In [57]:
df['AYB'].std()

33.64023357603095

In [58]:
df.groupby(['AYB', 'ASSESSMENT_SUBNBHD'])

In [60]:
df.groupby(['AYB', 'ASSESSMENT_SUBNBHD','Grade'])

KeyError: 'Grade'

In [61]:
df.groupby(['AYB', 'ASSESSMENT_SUBNBHD','GRADE'])

In [62]:
df.groupby(['AYB', 'ASSESSMENT_SUBNBHD','GRADE','QUADRANT','PRICE',])

In [63]:
df.dtypes

Unnamed: 0              int64
BATHRM                  int64
HF_BATHRM               int64
HEAT                   object
AC                     object
NUM_UNITS             float64
ROOMS                   int64
BEDRM                   int64
AYB                   float64
YR_RMDL               float64
EYB                     int64
STORIES               float64
SALEDATE               object
PRICE                 float64
QUALIFIED              object
SALE_NUM                int64
GBA                   float64
BLDG_NUM                int64
STYLE                  object
STRUCT                 object
GRADE                  object
CNDTN                  object
EXTWALL                object
ROOF                   object
INTWALL                object
KITCHENS              float64
FIREPLACES              int64
USECODE                 int64
LANDAREA                int64
GIS_LAST_MOD_DTTM      object
SOURCE                 object
CMPLX_NUM             float64
LIVING_GBA            float64
FULLADDRESS            object
CITY                   object
STATE                  object
ZIPCODE               float64
NATIONALGRID           object
LATITUDE              float64
LONGITUDE             float64
ASSESSMENT_NBHD        object
ASSESSMENT_SUBNBHD     object
CENSUS_TRACT          float64
CENSUS_BLOCK           object
WARD                   object
SQUARE                 object
X                     float64
Y                     float64
QUADRANT               object
dtype: object

In [64]:
pd.pivot_table

In [65]:
pd.pivot_table(df, values=['AYB'],index=['ASSESSMENT_SUBNBHD'] )

                                   AYB
ASSESSMENT_SUBNBHD
001 A American University  1934.508728
001 B American University  1946.913970
001 C American University  1941.039088
002 A Anacostia            1940.461340
002 B Anacostia            1939.491259
004 A Berkley              1947.068702
004 B Berkley              1966.912281
004 C Berkley              1979.993464
005 A Brentwood            1945.671296
005 B Brentwood            1949.223404
006 A Brightwood           1940.913943
006 B Brightwood           1942.359638
006 C Brightwood           1928.957553
006 D Brightwood           1937.896296
006 E Brightwood           1931.688119
007 A Brookland            1945.826490
007 B Brookland            1958.501250
007 C Brookland            1942.086154
007 D Brookland            1927.801199
007 E Brookland            1945.643678
008 A Burleith             1925.500000
008 B Burleith             1987.329588
009 A Capitol Hill         1905.265841
009 B Capitol Hill         1911.292754
009 C Capitol Hill         1909.838770
011 A Chevy Chase          1945.014262
011 B Chevy Chase          1932.597868
011 C Chevy Chase          1934.478463
011 D Chevy Chase          1944.838117
011 E Chevy Chase          1942.098830
...                                ...
040 C Old City 2           1963.512998
040 D Old City 2           1927.256189
040 E Old City 2           1929.760364
040 F Old City 2           1968.671562
040 G Old City 2           1916.219035
041 A Palisades            1945.816514
041 B Palisades            1955.909201
042 A Petworth             1919.765777
042 B Petworth             1926.779636
042 C Petworth             1932.498256
043 A Randle Heights       1938.488962
043 B Randle Heights       1967.300350
043 C Randle Heights       1960.038012
043 D Randle Heights       2004.360153
049 A 16th Street Heights  1925.113010
049 B 16th Street Heights  1925.164510
049 C 16th Street Heights  1927.360465
050 A Spring Valley        1990.619318
050 B Spring Valley        1947.514412
050 C Spring Valley        1953.219101
050 D Spring Valley        1951.364341
052 A Trinidad             1927.369565
052 B Trinidad             1938.836461
052 C Trinidad             1937.670431
054 A Wesley Heights       1938.291667
054 B Wesley Heights       1968.435669
056 A Woodridge            1928.780488
056 B Woodridge            1932.425243
056 C Woodridge            1938.520505
056 D Woodridge            1937.659176

[121 rows x 1 columns]

In [72]:
pd.pivot_table(df, values=['AYB'], index=['PRICE'])

                     AYB
PRICE
1.0          1953.000000
10.0         1917.750000
250.0        1914.428571
500.0        1908.333333
936.0        1900.000000
1000.0       1935.800000
1377.0       1900.000000
2000.0       1914.000000
3000.0       1999.500000
3270.0       1950.000000
3523.0       1949.000000
3997.0       1948.000000
4101.0       1945.000000
4156.0       1937.000000
4500.0       1907.000000
4850.0       1998.666667
5000.0       1927.750000
5115.0       2005.000000
5185.0       2014.000000
5247.0       1908.000000
5400.0       1918.000000
5453.0       1964.000000
5522.0       1940.000000
5643.0       2008.000000
5964.0       1927.000000
6000.0       1931.500000
6826.0       1965.000000
6950.0       1875.000000
7000.0       2002.000000
7425.0       1953.000000
...                  ...
7950000.0    1929.000000
8000000.0    2003.000000
8100000.0    1928.000000
8243685.0    1989.000000
8375000.0    1930.000000
8400000.0    1928.000000
8450000.0    1914.500000
8500000.0    1911.000000
8600000.0    1870.000000
9000000.0    1926.000000
9100000.0    1925.000000
10400000.0   1930.000000
10750000.0   1927.000000
11000000.0   1928.666667
11111111.0   1941.000000
11984000.0   1961.000000
12250000.0   2008.000000
12780000.0   1944.000000
14000000.0   1962.000000
14157126.0   1980.000000
15000000.0   1986.000000
16100000.0   1805.000000
18000000.0   1994.000000
22000000.0   1801.000000
23960287.0   1805.000000
25000000.0   2004.000000
25100000.0   2002.000000
53696391.0   1963.000000
53969391.0   1963.000000
137427545.0  1986.322314

[13473 rows x 1 columns]

In [73]:
pd.pivot_table(df.groupby(['AYB','PRICE'])values=['AYB'])

SyntaxError: invalid syntax (<ipython-input-73-7a169c4ed118>, line 1)

In [1]:
 df['ASSESSMENT_SUBNBHD'].value_counts()

NameError: name 'df' is not defined

In [2]:
pd.pivot_table(df, values=['ASSESSMENT_SUBNBHD'], index=['PRICE'])

NameError: name 'pd' is not defined

In [5]:
location = "DC_Properties.csv"
df = pd.read_csv(location)

NameError: name 'pd' is not defined

In [8]:

import pandas as pd

In [9]:
import csv

In [11]:
location = "DC_Properties.csv"

In [12]:
df = pd.read_csv(location)

C:\Users\kenbe\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (18,19,20,21,22,23,24,33,34,35,37,43,45) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [13]:
import csv

In [14]:
df.head()

,Unnamed: 0,BATHRM,HF_BATHRM,HEAT,AC,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,...,LONGITUDE,ASSESSMENT_NBHD,ASSESSMENT_SUBNBHD,CENSUS_TRACT,CENSUS_BLOCK,WARD,SQUARE,X,Y,QUADRANT
0,0,4,0,Warm Cool,Y,2.0,8,4,1910.0,1988.0,...,-77.040832,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
1,1,3,1,Warm Cool,Y,2.0,11,5,1898.0,2007.0,...,-77.040764,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
2,2,3,1,Hot Water Rad,Y,2.0,9,5,1910.0,2009.0,...,-77.040678,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
3,3,3,1,Hot Water Rad,Y,2.0,8,5,1900.0,2003.0,...,-77.040629,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
4,4,2,1,Warm Cool,Y,1.0,11,3,1913.0,2012.0,...,-77.039361,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW

In [15]:
pd.pivot_table(df, values=['ASSESSMENT_SUBNBHD'], index=['PRICE'])

DataError: No numeric types to aggregate

In [16]:
pd.pivot_table(df, values=['AYB'], index=['PRICE'])

                     AYB
PRICE
1.0          1953.000000
10.0         1917.750000
250.0        1914.428571
500.0        1908.333333
936.0        1900.000000
1000.0       1935.800000
1377.0       1900.000000
2000.0       1914.000000
3000.0       1999.500000
3270.0       1950.000000
3523.0       1949.000000
3997.0       1948.000000
4101.0       1945.000000
4156.0       1937.000000
4500.0       1907.000000
4850.0       1998.666667
5000.0       1927.750000
5115.0       2005.000000
5185.0       2014.000000
5247.0       1908.000000
5400.0       1918.000000
5453.0       1964.000000
5522.0       1940.000000
5643.0       2008.000000
5964.0       1927.000000
6000.0       1931.500000
6826.0       1965.000000
6950.0       1875.000000
7000.0       2002.000000
7425.0       1953.000000
...                  ...
7950000.0    1929.000000
8000000.0    2003.000000
8100000.0    1928.000000
8243685.0    1989.000000
8375000.0    1930.000000
8400000.0    1928.000000
8450000.0    1914.500000
8500000.0    1911.000000
8600000.0    1870.000000
9000000.0    1926.000000
9100000.0    1925.000000
10400000.0   1930.000000
10750000.0   1927.000000
11000000.0   1928.666667
11111111.0   1941.000000
11984000.0   1961.000000
12250000.0   2008.000000
12780000.0   1944.000000
14000000.0   1962.000000
14157126.0   1980.000000
15000000.0   1986.000000
16100000.0   1805.000000
18000000.0   1994.000000
22000000.0   1801.000000
23960287.0   1805.000000
25000000.0   2004.000000
25100000.0   2002.000000
53696391.0   1963.000000
53969391.0   1963.000000
137427545.0  1986.322314

[13473 rows x 1 columns]

In [17]:
pd.pivot_table(df, values=['ASSESSMENT_SUBNBHD'], index=['PRICE'])

DataError: No numeric types to aggregate

In [18]:
pd.pivot_table(df, values=['WARD'], index=['PRICE'])

DataError: No numeric types to aggregate

In [19]:
pd.pivot_table(df, values=['AYB'], index=['WARD'])

                AYB
WARD
Ward 1  1932.394815
Ward 2  1948.277683
Ward 3  1947.718658
Ward 4  1934.738544
Ward 5  1938.522708
Ward 6  1933.772784
Ward 7  1950.822649
Ward 8  1957.728817

In [20]:
pd.pivot_table(df, values=['PRICE'], index=['WARD'])

               PRICE
WARD
Ward 1  5.738363e+05
Ward 2  1.098570e+06
Ward 3  3.077716e+06
Ward 4  4.899224e+05
Ward 5  3.952432e+05
Ward 6  5.268684e+05
Ward 7  2.339222e+05
Ward 8  2.715224e+05

In [21]:
pd.pivot_table(df, values=['WARD'], index=['PRICE'])

DataError: No numeric types to aggregate

In [22]:
df['WARD'].value_counts()

Ward 6    23973
Ward 3    23688
Ward 4    22202
Ward 2    22167
Ward 5    21359
Ward 1    17455
Ward 7    17206
Ward 8    10906
Name: WARD, dtype: int64

In [23]:
df.count

<bound method DataFrame.count of         Unnamed: 0  BATHRM  HF_BATHRM           HEAT AC  NUM_UNITS  ROOMS  \
0                0       4          0      Warm Cool  Y        2.0      8
1                1       3          1      Warm Cool  Y        2.0     11
2                2       3          1  Hot Water Rad  Y        2.0      9
3                3       3          1  Hot Water Rad  Y        2.0      8
4                4       2          1      Warm Cool  Y        1.0     11
5                5       3          2  Hot Water Rad  Y        1.0     10
6                6       1          0      Warm Cool  Y        2.0      5
7                7       3          1  Hot Water Rad  Y        2.0      8
8                8       3          1      Warm Cool  Y        2.0      7
9                9       1          1  Hot Water Rad  Y        1.0      6
10              10       3          0     Forced Air  N        3.0     12
11              11       5          0  Hot Water Rad  Y        3.0     16
12              12       2          0  Hot Water Rad  N        2.0      9
13              13       2          0      Warm Cool  Y        2.0     11
14              14       3          1      Warm Cool  Y        2.0      5
15              15       2          1      Warm Cool  Y        2.0      9
16              16       3          1      Warm Cool  Y        1.0      8
17              17       2          0  Hot Water Rad  N        1.0      6
18              18       3          1  Hot Water Rad  Y        2.0     10
19              19       3          1  Hot Water Rad  Y        2.0      9
20              20       3          1  Hot Water Rad  Y        1.0     14
21              21       3          0     Forced Air  Y        2.0     12
22              22       1          0     Forced Air  Y        1.0      6
23              23       2          1     Forced Air  Y        1.0      5
24              24       2          1  Hot Water Rad  Y        1.0      8
25              25       1          0  Hot Water Rad  N        1.0      8
26              26       1          0  Hot Water Rad  N        1.0     10
27              27       3          0  Hot Water Rad  Y        4.0      9
28              28       3          0      Warm Cool  Y        2.0     10
29              29       3          1     Forced Air  Y        2.0     11
...            ...     ...        ...            ... ..        ...    ...
158927      158927       2          0        Ht Pump  Y        NaN      6
158928      158928       2          1        Ht Pump  Y        NaN      5
158929      158929       2          1        Ht Pump  Y        NaN      5
158930      158930       2          0     Forced Air  N        NaN      4
158931      158931       2          1     Forced Air  N        NaN      4
158932      158932       2          1     Forced Air  N        NaN      4
158933      158933       2          0        Ht Pump  Y        NaN      4
158934      158934       1          1        Ht Pump  Y        NaN      3
158935      158935       1          0        Ht Pump  Y        NaN      3
158936      158936       1          0        Ht Pump  Y        NaN      3
158937      158937       1          0     Forced Air  Y        NaN      4
158938      158938       2          0      Warm Cool  Y        NaN      7
158939      158939       1          0     Forced Air  Y        NaN      4
158940      158940       2          0     Forced Air  Y        NaN      7
158941      158941       1          0     Forced Air  Y        NaN      4
158942      158942       2          0     Forced Air  Y        NaN      7
158943      158943       2          1     Forced Air  Y        NaN      5
158944      158944       2          1     Forced Air  Y        NaN      5
158945      158945       1          0     Forced Air  Y        NaN      3
158946      158946       1          0     Forced Air  Y        NaN      4
158947      158947       2          0     Forced Air  Y        NaN      4
158948      158948       2          0     Forced Air  Y        NaN      4
158949      158949       1          1     Forced Air  Y        NaN      4
158950      158950       3          0     Forced Air  Y        NaN      5
158951      158951       3          1     Forced Air  Y        NaN      5
158952      158952       1          0     Forced Air  Y        NaN      3
158953      158953       1          0     Forced Air  Y        NaN      4
158954      158954       2          0     Forced Air  Y        NaN      4
158955      158955       1          0      Warm Cool  Y        NaN      2
158956      158956       1          0      Warm Cool  Y        NaN      2

        BEDRM     AYB  YR_RMDL   ...     LONGITUDE       ASSESSMENT_NBHD  \
0           4  1910.0   1988.0   ...    -77.040832            Old City 2
1           5  1898.0   2007.0   ...    -77.040764            Old City 2
2           5  1910.0   2009.0   ...    -77.040678            Old City 2
3           5  1900.0   2003.0   ...    -77.040629            Old City 2
4           3  1913.0   2012.0   ...    -77.039361            Old City 2
5           5  1913.0      NaN   ...    -77.039715            Old City 2
6           2  1917.0   1988.0   ...    -77.041055            Old City 2
7           4  1906.0   2011.0   ...    -77.040129            Old City 2
8           3  1908.0   2008.0   ...    -77.039903            Old City 2
9           2  1908.0   1979.0   ...    -77.040081            Old City 2
10          5  1890.0   1950.0   ...    -77.040760            Old City 2
11          6  1905.0      NaN   ...    -77.039718            Old City 2
12          5  1894.0   1979.0   ...    -77.039569            Old City 2
13          5  1885.0   1979.0   ...    -77.039644            Old City 2
14          3  1917.0   2000.0   ...    -77.039716            Old City 2
15          4  1908.0   1990.0   ...    -77.039784            Old City 2
16          3  1908.0   2006.0   ...    -77.039844            Old City 2
17          3  1908.0   1987.0   ...    -77.039961            Old City 2
18          4  1908.0   2006.0   ...    -77.040020            Old City 2
19          3  1908.0   2013.0   ...    -77.040138            Old City 2
20          5  1880.0   2009.0   ...    -77.033774            Old City 2
21          3  1880.0   2009.0   ...    -77.033838            Old City 2
22          3  1880.0   2010.0   ...    -77.033925            Old City 2
23          3  1880.0   2010.0   ...    -77.033972            Old City 2
24          3  1880.0   2004.0   ...    -77.034070            Old City 2
25          4  1880.0   2010.0   ...    -77.034156            Old City 2
26          5  1900.0   2004.0   ...    -77.034258            Old City 2
27          3  1900.0   1963.0   ...    -77.034182            Old City 2
28          4  1900.0   1960.0   ...    -77.034119            Old City 2
29          3  1900.0   2014.0   ...    -77.034051            Old City 2
...       ...     ...      ...   ...           ...                   ...
158927      3  1993.0   1993.0   ...    -77.019274            Old City 2
158928      2  2013.0      NaN   ...    -77.019274            Old City 2
158929      2  2013.0      NaN   ...    -77.019274            Old City 2
158930      2  1900.0   2003.0   ...    -77.019243            Old City 2
158931      2  1900.0   2003.0   ...    -77.019243            Old City 2
158932      2  1900.0   2003.0   ...    -77.019243            Old City 2
158933      2  1880.0   2016.0   ...    -77.019243            Old City 2
158934      1  1880.0   2016.0   ...    -77.019243            Old City 2
158935      1  1880.0   2016.0   ...    -77.019243            Old City 2
158936      1  1880.0   2016.0   ...    -77.019243            Old City 2
158937      2  1992.0   1992.0   ...    -77.019420            Old City 2
158938      4  1992.0   1992.0   ...    -77.019420            Old City 2
158939      2  1992.0   1992.0   ...    -77.019420            Old City 2
158940      4  1992.0   1992.0   ...    -77.019420            Old City 2
158941      2  1992.0   1992.0   ...    -77.019420            Old City 2
158942      4  1992.0   1992.0   ...    -77.019420            Old City 2
158943      2  2004.0   2004.0   ...    -77.019420            Old City 2
158944      2  2004.0   2004.0   ...    -77.019420            Old City 2
158945      1  1938.0   2006.0   ...    -77.019420            Old City 2
158946      2  1938.0   2006.0   ...    -77.019420            Old City 2
158947      2  1938.0   2006.0   ...    -77.019420            Old City 2
158948      2  1938.0   2006.0   ...    -77.019420            Old City 2
158949      1  1938.0   2006.0   ...    -77.019420            Old City 2
158950      3  1938.0   2006.0   ...    -77.019420            Old City 2
158951      3  1938.0   2006.0   ...    -77.019420            Old City 2
158952      1  1938.0   2006.0   ...    -77.019420            Old City 2
158953      2  1938.0   2006.0   ...    -77.019420            Old City 2
158954      2  1920.0   2007.0   ...    -77.019420            Old City 2
158955      0  1965.0      NaN   ...    -77.018230  Southwest Waterfront
158956      0  1965.0      NaN   ...    -77.018230  Southwest Waterfront

       ASSESSMENT_SUBNBHD  CENSUS_TRACT CENSUS_BLOCK    WARD  SQUARE  \
0        040 D Old City 2        4201.0  004201 2006  Ward 2     152
1        040 D Old City 2        4201.0  004201 2006  Ward 2     152
2        040 D Old City 2        4201.0  004201 2006  Ward 2     152
3        040 D Old City 2        4201.0  004201 2006  Ward 2     152
4        040 D Old City 2        4201.0  004201 2006  Ward 2     152
5        040 D Old City 2        4201.0  004201 2006  Ward 2     152
6        040 D Old City 2        4201.0  004201 2005  Ward 2     152
7        040 D Old City 2        4201.0  004201 2005  Ward 2     152
8        040 D Old City 2        4201.0  004201 2005  Ward 2     152
9        040 D Old City 2        4201.0  004201 2005  Ward 2     152
10       040 D Old City 2        4201.0  004201 2005  Ward 2     152
11       040 D Old City 2        4201.0  004201 2005  Ward 2     152
12       040 D Old City 2        4201.0  004201 2005  Ward 2     152
13       040 D Old City 2        4201.0  004201 2005  Ward 2     152
14       040 D Old City 2        4201.0  004201 2005  Ward 2     152
15       040 D Old City 2        4201.0  004201 2005  Ward 2     152
16       040 D Old City 2        4201.0  004201 2005  Ward 2     152
17       040 D Old City 2        4201.0  004201 2005  Ward 2     152
18       040 D Old City 2        4201.0  004201 2005  Ward 2     152
19       040 D Old City 2        4201.0  004201 2005  Ward 2     152
20       040 E Old City 2        5201.0  005201 4003  Ward 2     208
21       040 E Old City 2        5201.0  005201 4003  Ward 2     208
22       040 E Old City 2        5201.0  005201 4003  Ward 2     208
23       040 E Old City 2        5201.0  005201 4003  Ward 2     208
24       040 E Old City 2        5201.0  005201 4003  Ward 2     208
25       040 E Old City 2        5201.0  005201 4003  Ward 2     208
26       040 E Old City 2        5201.0  005201 4003  Ward 2     208
27       040 E Old City 2        5201.0  005201 4003  Ward 2     208
28       040 E Old City 2        5201.0  005201 4003  Ward 2     208
29       040 E Old City 2        5201.0  005201 4003  Ward 2     208
...                   ...           ...          ...     ...     ...
158927   040 G Old City 2        4801.0          NaN  Ward 6     475
158928   040 G Old City 2        4801.0          NaN  Ward 6     475
158929   040 G Old City 2        4801.0          NaN  Ward 6     475
158930   040 B Old City 2        4801.0          NaN  Ward 6     476
158931   040 B Old City 2        4801.0          NaN  Ward 6     476
158932   040 B Old City 2        4801.0          NaN  Ward 6     476
158933   040 B Old City 2        4801.0          NaN  Ward 6     476
158934   040 B Old City 2        4801.0          NaN  Ward 6     476
158935   040 B Old City 2        4801.0          NaN  Ward 6     476
158936   040 B Old City 2        4801.0          NaN  Ward 6     476
158937   040 B Old City 2        4801.0          NaN  Ward 6     477
158938   040 B Old City 2        4801.0          NaN  Ward 6     477
158939   040 B Old City 2        4801.0          NaN  Ward 6     477
158940   040 B Old City 2        4801.0          NaN  Ward 6     477
158941   040 B Old City 2        4801.0          NaN  Ward 6     477
158942   040 B Old City 2        4801.0          NaN  Ward 6     477
158943   040 B Old City 2        4801.0          NaN  Ward 6     477
158944   040 B Old City 2        4801.0          NaN  Ward 6     477
158945   040 B Old City 2        4801.0          NaN  Ward 6     477
158946   040 B Old City 2        4801.0          NaN  Ward 6     477
158947   040 B Old City 2        4801.0          NaN  Ward 6     477
158948   040 B Old City 2        4801.0          NaN  Ward 6     477
158949   040 B Old City 2        4801.0          NaN  Ward 6     477
158950   040 B Old City 2        4801.0          NaN  Ward 6     477
158951   040 B Old City 2        4801.0          NaN  Ward 6     477
158952   040 B Old City 2        4801.0          NaN  Ward 6     477
158953   040 B Old City 2        4801.0          NaN  Ward 6     477
158954   040 B Old City 2        4801.0          NaN  Ward 6     477
158955                NaN       11000.0          NaN  Ward 6     504
158956                NaN       11000.0          NaN  Ward 6     504

                X          Y QUADRANT
0      -77.040429  38.914881       NW
1      -77.040429  38.914881       NW
2      -77.040429  38.914881       NW
3      -77.040429  38.914881       NW
4      -77.040429  38.914881       NW
5      -77.040429  38.914881       NW
6      -77.040429  38.914881       NW
7      -77.040429  38.914881       NW
8      -77.040429  38.914881       NW
9      -77.040429  38.914881       NW
10     -77.040429  38.914881       NW
11     -77.040429  38.914881       NW
12     -77.040429  38.914881       NW
13     -77.040429  38.914881       NW
14     -77.040429  38.914881       NW
15     -77.040429  38.914881       NW
16     -77.040429  38.914881       NW
17     -77.040429  38.914881       NW
18     -77.040429  38.914881       NW
19     -77.040429  38.914881       NW
20     -77.033366  38.911716       NW
21     -77.033366  38.911716       NW
22     -77.033366  38.911716       NW
23     -77.033366  38.911716       NW
24     -77.033366  38.911716       NW
25     -77.033366  38.911716       NW
26     -77.033366  38.911716       NW
27     -77.033366  38.911716       NW
28     -77.033366  38.911716       NW
29     -77.033366  38.911716       NW
...           ...        ...      ...
158927 -77.019277  38.914287       NW
158928 -77.019277  38.914287       NW
158929 -77.019277  38.914287       NW
158930 -77.019245  38.912954       NW
158931 -77.019245  38.912954       NW
158932 -77.019245  38.912954       NW
158933 -77.019245  38.912954       NW
158934 -77.019245  38.912954       NW
158935 -77.019245  38.912954       NW
158936 -77.019245  38.912954       NW
158937 -77.019422  38.911848       NW
158938 -77.019422  38.911848       NW
158939 -77.019422  38.911848       NW
158940 -77.019422  38.911848       NW
158941 -77.019422  38.911848       NW
158942 -77.019422  38.911848       NW
158943 -77.019422  38.911848       NW
158944 -77.019422  38.911848       NW
158945 -77.019422  38.911848       NW
158946 -77.019422  38.911848       NW
158947 -77.019422  38.911848       NW
158948 -77.019422  38.911848       NW
158949 -77.019422  38.911848       NW
158950 -77.019422  38.911848       NW
158951 -77.019422  38.911848       NW
158952 -77.019422  38.911848       NW
158953 -77.019422  38.911848       NW
158954 -77.019422  38.911848       NW
158955 -77.018232  38.872961       SW
158956 -77.018232  38.872961       SW

[158957 rows x 49 columns]>

In [24]:
df['Unamed'].value_counts()

KeyError: 'Unamed'

In [25]:
df['Unnamed'].value_counts()

KeyError: 'Unnamed'

In [30]:
WARD = ['Ward 6', 'Ward 8']
QUADRANT = ['NW', 'SW']
df

,Unnamed: 0,BATHRM,HF_BATHRM,HEAT,AC,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,...,LONGITUDE,ASSESSMENT_NBHD,ASSESSMENT_SUBNBHD,CENSUS_TRACT,CENSUS_BLOCK,WARD,SQUARE,X,Y,QUADRANT
0,0,4,0,Warm Cool,Y,2.0,8,4,1910.0,1988.0,...,-77.040832,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
1,1,3,1,Warm Cool,Y,2.0,11,5,1898.0,2007.0,...,-77.040764,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
2,2,3,1,Hot Water Rad,Y,2.0,9,5,1910.0,2009.0,...,-77.040678,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
3,3,3,1,Hot Water Rad,Y,2.0,8,5,1900.0,2003.0,...,-77.040629,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
4,4,2,1,Warm Cool,Y,1.0,11,3,1913.0,2012.0,...,-77.039361,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
5,5,3,2,Hot Water Rad,Y,1.0,10,5,1913.0,NaN,...,-77.039715,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
6,6,1,0,Warm Cool,Y,2.0,5,2,1917.0,1988.0,...,-77.041055,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
7,7,3,1,Hot Water Rad,Y,2.0,8,4,1906.0,2011.0,...,-77.040129,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
8,8,3,1,Warm Cool,Y,2.0,7,3,1908.0,2008.0,...,-77.039903,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
9,9,1,1,Hot Water Rad,Y,1.0,6,2,1908.0,1979.0,...,-77.040081,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
10,10,3,0,Forced Air,N,3.0,12,5,1890.0,1950.0,...,-77.040760,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
11,11,5,0,Hot Water Rad,Y,3.0,16,6,1905.0,NaN,...,-77.039718,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
12,12,2,0,Hot Water Rad,N,2.0,9,5,1894.0,1979.0,...,-77.039569,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
13,13,2,0,Warm Cool,Y,2.0,11,5,1885.0,1979.0,...,-77.039644,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
14,14,3,1,Warm Cool,Y,2.0,5,3,1917.0,2000.0,...,-77.039716,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
15,15,2,1,Warm Cool,Y,2.0,9,4,1908.0,1990.0,...,-77.039784,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
16,16,3,1,Warm Cool,Y,1.0,8,3,1908.0,2006.0,...,-77.039844,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
17,17,2,0,Hot Water Rad,N,1.0,6,3,1908.0,1987.0,...,-77.039961,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
18,18,3,1,Hot Water Rad,Y,2.0,10,4,1908.0,2006.0,...,-77.040020,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
19,19,3,1,Hot Water Rad,Y,2.0,9,3,1908.0,2013.0,...,-77.040138,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
20,20,3,1,Hot Water Rad,Y,1.0,14,5,1880.0,2009.0,...,-77.033774,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
21,21,3,0,Forced Air,Y,2.0,12,3,1880.0,2009.0,...,-77.033838,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
22,22,1,0,Forced Air,Y,1.0,6,3,1880.0,2010.0,...,-77.033925,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
23,23,2,1,Forced Air,Y,1.0,5,3,1880.0,2010.0,...,-77.033972,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
24,24,2,1,Hot Water Rad,Y,1.0,8,3,1880.0,2004.0,...,-77.034070,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
25,25,1,0,Hot Water Rad,N,1.0,8,4,1880.0,2010.0,...,-77.034156,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
26,26,1,0,Hot Water Rad,N,1.0,10,5,1900.0,2004.0,...,-77.034258,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
27,27,3,0,Hot Water Rad,Y,4.0,9,3,1900.0,1963.0,...,-77.034182,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
28,28,3,0,Warm Cool,Y,2.0,10,4,1900.0,1960.0,...,-77.034119,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
29,29,3,1,Forced Air,Y,2.0,11,3,1900.0,2014.0,...,-77.034051,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158927,158927,2,0,Ht Pump,Y,NaN,6,3,1993.0,1993.0,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158928,158928,2,1,Ht Pump,Y,NaN,5,2,2013.0,NaN,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158929,158929,2,1,Ht Pump,Y,NaN,5,2,2013.0,NaN,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158930,158930,2,0,Forced Air,N,NaN,4,2,1900.0,2003.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158931,158931,2,1,Forced Air,N,NaN,4,2,1900.0,2003.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158932,158932,2,1,Forced Air,N,NaN,4,2,1900.0,2003.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158933,158933,2,0,Ht Pump,Y,NaN,4,2,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158934,158934,1,1,Ht Pump,Y,NaN,3,1,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158935,158935,1,0,Ht Pump,Y,NaN,3,1,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158936,158936,1,0,Ht Pump,Y,NaN,3,1,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158937,158937,1,0,Forced Air,Y,NaN,4,2,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158938,158938,2,0,Warm Cool,Y,NaN,7,4,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158939,158939,1,0,Forced Air,Y,NaN,4,2,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158940,158940,2,0,Forced Air,Y,NaN,7,4,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158941,158941,1,0,Forced Air,Y,NaN,4,2,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158942,158942,2,0,Forced Air,Y,NaN,7,4,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158943,158943,2,1,Forced Air,Y,NaN,5,2,2004.0,2004.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158944,158944,2,1,Forced Air,Y,NaN,5,2,2004.0,2004.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158945,158945,1,0,Forced Air,Y,NaN,3,1,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158946,158946,1,0,Forced Air,Y,NaN,4,2,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158947,158947,2,0,Forced Air,Y,NaN,4,2,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158948,158948,2,0,Forced Air,Y,NaN,4,2,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158949,158949,1,1,Forced Air,Y,NaN,4,1,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158950,158950,3,0,Forced Air,Y,NaN,5,3,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158951,158951,3,1,Forced Air,Y,NaN,5,3,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158952,158952,1,0,Forced Air,Y,NaN,3,1,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158953,158953,1,0,Forced Air,Y,NaN,4,2,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158954,158954,2,0,Forced Air,Y,NaN,4,2,1920.0,2007.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158955,158955,1,0,Warm Cool,Y,NaN,2,0,1965.0,NaN,...,-77.018230,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,504,-77.018232,38.872961,SW
158956,158956,1,0,Warm Cool,Y,NaN,2,0,1965.0,NaN,...,-77.018230,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,504,-77.018232,38.872961,SW

In [31]:
df.head

<bound method NDFrame.head of         Unnamed: 0  BATHRM  HF_BATHRM           HEAT AC  NUM_UNITS  ROOMS  \
0                0       4          0      Warm Cool  Y        2.0      8
1                1       3          1      Warm Cool  Y        2.0     11
2                2       3          1  Hot Water Rad  Y        2.0      9
3                3       3          1  Hot Water Rad  Y        2.0      8
4                4       2          1      Warm Cool  Y        1.0     11
5                5       3          2  Hot Water Rad  Y        1.0     10
6                6       1          0      Warm Cool  Y        2.0      5
7                7       3          1  Hot Water Rad  Y        2.0      8
8                8       3          1      Warm Cool  Y        2.0      7
9                9       1          1  Hot Water Rad  Y        1.0      6
10              10       3          0     Forced Air  N        3.0     12
11              11       5          0  Hot Water Rad  Y        3.0     16
12              12       2          0  Hot Water Rad  N        2.0      9
13              13       2          0      Warm Cool  Y        2.0     11
14              14       3          1      Warm Cool  Y        2.0      5
15              15       2          1      Warm Cool  Y        2.0      9
16              16       3          1      Warm Cool  Y        1.0      8
17              17       2          0  Hot Water Rad  N        1.0      6
18              18       3          1  Hot Water Rad  Y        2.0     10
19              19       3          1  Hot Water Rad  Y        2.0      9
20              20       3          1  Hot Water Rad  Y        1.0     14
21              21       3          0     Forced Air  Y        2.0     12
22              22       1          0     Forced Air  Y        1.0      6
23              23       2          1     Forced Air  Y        1.0      5
24              24       2          1  Hot Water Rad  Y        1.0      8
25              25       1          0  Hot Water Rad  N        1.0      8
26              26       1          0  Hot Water Rad  N        1.0     10
27              27       3          0  Hot Water Rad  Y        4.0      9
28              28       3          0      Warm Cool  Y        2.0     10
29              29       3          1     Forced Air  Y        2.0     11
...            ...     ...        ...            ... ..        ...    ...
158927      158927       2          0        Ht Pump  Y        NaN      6
158928      158928       2          1        Ht Pump  Y        NaN      5
158929      158929       2          1        Ht Pump  Y        NaN      5
158930      158930       2          0     Forced Air  N        NaN      4
158931      158931       2          1     Forced Air  N        NaN      4
158932      158932       2          1     Forced Air  N        NaN      4
158933      158933       2          0        Ht Pump  Y        NaN      4
158934      158934       1          1        Ht Pump  Y        NaN      3
158935      158935       1          0        Ht Pump  Y        NaN      3
158936      158936       1          0        Ht Pump  Y        NaN      3
158937      158937       1          0     Forced Air  Y        NaN      4
158938      158938       2          0      Warm Cool  Y        NaN      7
158939      158939       1          0     Forced Air  Y        NaN      4
158940      158940       2          0     Forced Air  Y        NaN      7
158941      158941       1          0     Forced Air  Y        NaN      4
158942      158942       2          0     Forced Air  Y        NaN      7
158943      158943       2          1     Forced Air  Y        NaN      5
158944      158944       2          1     Forced Air  Y        NaN      5
158945      158945       1          0     Forced Air  Y        NaN      3
158946      158946       1          0     Forced Air  Y        NaN      4
158947      158947       2          0     Forced Air  Y        NaN      4
158948      158948       2          0     Forced Air  Y        NaN      4
158949      158949       1          1     Forced Air  Y        NaN      4
158950      158950       3          0     Forced Air  Y        NaN      5
158951      158951       3          1     Forced Air  Y        NaN      5
158952      158952       1          0     Forced Air  Y        NaN      3
158953      158953       1          0     Forced Air  Y        NaN      4
158954      158954       2          0     Forced Air  Y        NaN      4
158955      158955       1          0      Warm Cool  Y        NaN      2
158956      158956       1          0      Warm Cool  Y        NaN      2

        BEDRM     AYB  YR_RMDL   ...     LONGITUDE       ASSESSMENT_NBHD  \
0           4  1910.0   1988.0   ...    -77.040832            Old City 2
1           5  1898.0   2007.0   ...    -77.040764            Old City 2
2           5  1910.0   2009.0   ...    -77.040678            Old City 2
3           5  1900.0   2003.0   ...    -77.040629            Old City 2
4           3  1913.0   2012.0   ...    -77.039361            Old City 2
5           5  1913.0      NaN   ...    -77.039715            Old City 2
6           2  1917.0   1988.0   ...    -77.041055            Old City 2
7           4  1906.0   2011.0   ...    -77.040129            Old City 2
8           3  1908.0   2008.0   ...    -77.039903            Old City 2
9           2  1908.0   1979.0   ...    -77.040081            Old City 2
10          5  1890.0   1950.0   ...    -77.040760            Old City 2
11          6  1905.0      NaN   ...    -77.039718            Old City 2
12          5  1894.0   1979.0   ...    -77.039569            Old City 2
13          5  1885.0   1979.0   ...    -77.039644            Old City 2
14          3  1917.0   2000.0   ...    -77.039716            Old City 2
15          4  1908.0   1990.0   ...    -77.039784            Old City 2
16          3  1908.0   2006.0   ...    -77.039844            Old City 2
17          3  1908.0   1987.0   ...    -77.039961            Old City 2
18          4  1908.0   2006.0   ...    -77.040020            Old City 2
19          3  1908.0   2013.0   ...    -77.040138            Old City 2
20          5  1880.0   2009.0   ...    -77.033774            Old City 2
21          3  1880.0   2009.0   ...    -77.033838            Old City 2
22          3  1880.0   2010.0   ...    -77.033925            Old City 2
23          3  1880.0   2010.0   ...    -77.033972            Old City 2
24          3  1880.0   2004.0   ...    -77.034070            Old City 2
25          4  1880.0   2010.0   ...    -77.034156            Old City 2
26          5  1900.0   2004.0   ...    -77.034258            Old City 2
27          3  1900.0   1963.0   ...    -77.034182            Old City 2
28          4  1900.0   1960.0   ...    -77.034119            Old City 2
29          3  1900.0   2014.0   ...    -77.034051            Old City 2
...       ...     ...      ...   ...           ...                   ...
158927      3  1993.0   1993.0   ...    -77.019274            Old City 2
158928      2  2013.0      NaN   ...    -77.019274            Old City 2
158929      2  2013.0      NaN   ...    -77.019274            Old City 2
158930      2  1900.0   2003.0   ...    -77.019243            Old City 2
158931      2  1900.0   2003.0   ...    -77.019243            Old City 2
158932      2  1900.0   2003.0   ...    -77.019243            Old City 2
158933      2  1880.0   2016.0   ...    -77.019243            Old City 2
158934      1  1880.0   2016.0   ...    -77.019243            Old City 2
158935      1  1880.0   2016.0   ...    -77.019243            Old City 2
158936      1  1880.0   2016.0   ...    -77.019243            Old City 2
158937      2  1992.0   1992.0   ...    -77.019420            Old City 2
158938      4  1992.0   1992.0   ...    -77.019420            Old City 2
158939      2  1992.0   1992.0   ...    -77.019420            Old City 2
158940      4  1992.0   1992.0   ...    -77.019420            Old City 2
158941      2  1992.0   1992.0   ...    -77.019420            Old City 2
158942      4  1992.0   1992.0   ...    -77.019420            Old City 2
158943      2  2004.0   2004.0   ...    -77.019420            Old City 2
158944      2  2004.0   2004.0   ...    -77.019420            Old City 2
158945      1  1938.0   2006.0   ...    -77.019420            Old City 2
158946      2  1938.0   2006.0   ...    -77.019420            Old City 2
158947      2  1938.0   2006.0   ...    -77.019420            Old City 2
158948      2  1938.0   2006.0   ...    -77.019420            Old City 2
158949      1  1938.0   2006.0   ...    -77.019420            Old City 2
158950      3  1938.0   2006.0   ...    -77.019420            Old City 2
158951      3  1938.0   2006.0   ...    -77.019420            Old City 2
158952      1  1938.0   2006.0   ...    -77.019420            Old City 2
158953      2  1938.0   2006.0   ...    -77.019420            Old City 2
158954      2  1920.0   2007.0   ...    -77.019420            Old City 2
158955      0  1965.0      NaN   ...    -77.018230  Southwest Waterfront
158956      0  1965.0      NaN   ...    -77.018230  Southwest Waterfront

       ASSESSMENT_SUBNBHD  CENSUS_TRACT CENSUS_BLOCK    WARD  SQUARE  \
0        040 D Old City 2        4201.0  004201 2006  Ward 2     152
1        040 D Old City 2        4201.0  004201 2006  Ward 2     152
2        040 D Old City 2        4201.0  004201 2006  Ward 2     152
3        040 D Old City 2        4201.0  004201 2006  Ward 2     152
4        040 D Old City 2        4201.0  004201 2006  Ward 2     152
5        040 D Old City 2        4201.0  004201 2006  Ward 2     152
6        040 D Old City 2        4201.0  004201 2005  Ward 2     152
7        040 D Old City 2        4201.0  004201 2005  Ward 2     152
8        040 D Old City 2        4201.0  004201 2005  Ward 2     152
9        040 D Old City 2        4201.0  004201 2005  Ward 2     152
10       040 D Old City 2        4201.0  004201 2005  Ward 2     152
11       040 D Old City 2        4201.0  004201 2005  Ward 2     152
12       040 D Old City 2        4201.0  004201 2005  Ward 2     152
13       040 D Old City 2        4201.0  004201 2005  Ward 2     152
14       040 D Old City 2        4201.0  004201 2005  Ward 2     152
15       040 D Old City 2        4201.0  004201 2005  Ward 2     152
16       040 D Old City 2        4201.0  004201 2005  Ward 2     152
17       040 D Old City 2        4201.0  004201 2005  Ward 2     152
18       040 D Old City 2        4201.0  004201 2005  Ward 2     152
19       040 D Old City 2        4201.0  004201 2005  Ward 2     152
20       040 E Old City 2        5201.0  005201 4003  Ward 2     208
21       040 E Old City 2        5201.0  005201 4003  Ward 2     208
22       040 E Old City 2        5201.0  005201 4003  Ward 2     208
23       040 E Old City 2        5201.0  005201 4003  Ward 2     208
24       040 E Old City 2        5201.0  005201 4003  Ward 2     208
25       040 E Old City 2        5201.0  005201 4003  Ward 2     208
26       040 E Old City 2        5201.0  005201 4003  Ward 2     208
27       040 E Old City 2        5201.0  005201 4003  Ward 2     208
28       040 E Old City 2        5201.0  005201 4003  Ward 2     208
29       040 E Old City 2        5201.0  005201 4003  Ward 2     208
...                   ...           ...          ...     ...     ...
158927   040 G Old City 2        4801.0          NaN  Ward 6     475
158928   040 G Old City 2        4801.0          NaN  Ward 6     475
158929   040 G Old City 2        4801.0          NaN  Ward 6     475
158930   040 B Old City 2        4801.0          NaN  Ward 6     476
158931   040 B Old City 2        4801.0          NaN  Ward 6     476
158932   040 B Old City 2        4801.0          NaN  Ward 6     476
158933   040 B Old City 2        4801.0          NaN  Ward 6     476
158934   040 B Old City 2        4801.0          NaN  Ward 6     476
158935   040 B Old City 2        4801.0          NaN  Ward 6     476
158936   040 B Old City 2        4801.0          NaN  Ward 6     476
158937   040 B Old City 2        4801.0          NaN  Ward 6     477
158938   040 B Old City 2        4801.0          NaN  Ward 6     477
158939   040 B Old City 2        4801.0          NaN  Ward 6     477
158940   040 B Old City 2        4801.0          NaN  Ward 6     477
158941   040 B Old City 2        4801.0          NaN  Ward 6     477
158942   040 B Old City 2        4801.0          NaN  Ward 6     477
158943   040 B Old City 2        4801.0          NaN  Ward 6     477
158944   040 B Old City 2        4801.0          NaN  Ward 6     477
158945   040 B Old City 2        4801.0          NaN  Ward 6     477
158946   040 B Old City 2        4801.0          NaN  Ward 6     477
158947   040 B Old City 2        4801.0          NaN  Ward 6     477
158948   040 B Old City 2        4801.0          NaN  Ward 6     477
158949   040 B Old City 2        4801.0          NaN  Ward 6     477
158950   040 B Old City 2        4801.0          NaN  Ward 6     477
158951   040 B Old City 2        4801.0          NaN  Ward 6     477
158952   040 B Old City 2        4801.0          NaN  Ward 6     477
158953   040 B Old City 2        4801.0          NaN  Ward 6     477
158954   040 B Old City 2        4801.0          NaN  Ward 6     477
158955                NaN       11000.0          NaN  Ward 6     504
158956                NaN       11000.0          NaN  Ward 6     504

                X          Y QUADRANT
0      -77.040429  38.914881       NW
1      -77.040429  38.914881       NW
2      -77.040429  38.914881       NW
3      -77.040429  38.914881       NW
4      -77.040429  38.914881       NW
5      -77.040429  38.914881       NW
6      -77.040429  38.914881       NW
7      -77.040429  38.914881       NW
8      -77.040429  38.914881       NW
9      -77.040429  38.914881       NW
10     -77.040429  38.914881       NW
11     -77.040429  38.914881       NW
12     -77.040429  38.914881       NW
13     -77.040429  38.914881       NW
14     -77.040429  38.914881       NW
15     -77.040429  38.914881       NW
16     -77.040429  38.914881       NW
17     -77.040429  38.914881       NW
18     -77.040429  38.914881       NW
19     -77.040429  38.914881       NW
20     -77.033366  38.911716       NW
21     -77.033366  38.911716       NW
22     -77.033366  38.911716       NW
23     -77.033366  38.911716       NW
24     -77.033366  38.911716       NW
25     -77.033366  38.911716       NW
26     -77.033366  38.911716       NW
27     -77.033366  38.911716       NW
28     -77.033366  38.911716       NW
29     -77.033366  38.911716       NW
...           ...        ...      ...
158927 -77.019277  38.914287       NW
158928 -77.019277  38.914287       NW
158929 -77.019277  38.914287       NW
158930 -77.019245  38.912954       NW
158931 -77.019245  38.912954       NW
158932 -77.019245  38.912954       NW
158933 -77.019245  38.912954       NW
158934 -77.019245  38.912954       NW
158935 -77.019245  38.912954       NW
158936 -77.019245  38.912954       NW
158937 -77.019422  38.911848       NW
158938 -77.019422  38.911848       NW
158939 -77.019422  38.911848       NW
158940 -77.019422  38.911848       NW
158941 -77.019422  38.911848       NW
158942 -77.019422  38.911848       NW
158943 -77.019422  38.911848       NW
158944 -77.019422  38.911848       NW
158945 -77.019422  38.911848       NW
158946 -77.019422  38.911848       NW
158947 -77.019422  38.911848       NW
158948 -77.019422  38.911848       NW
158949 -77.019422  38.911848       NW
158950 -77.019422  38.911848       NW
158951 -77.019422  38.911848       NW
158952 -77.019422  38.911848       NW
158953 -77.019422  38.911848       NW
158954 -77.019422  38.911848       NW
158955 -77.018232  38.872961       SW
158956 -77.018232  38.872961       SW

[158957 rows x 49 columns]>

In [32]:
WARD = ['Ward 6', 'Ward 8']
QUADRANT = ['NW', 'SW']
col = ['Ward 6', 'Ward 8']
Degrees = ['NW', 'SW']

In [33]:
df = pd.DataFrame (data=WARD, columns=QUADRANT)

ValueError: Shape of passed values is (1, 2), indices imply (2, 2)

In [34]:
df = pd.DataFrame

In [35]:
#I was trying to show that the wards were differen based on price and other criteria for this project.

In [36]:
 df['WARD'].value_counts()

TypeError: 'type' object is not subscriptable